### ISSUE TITLE
Model.find with invalid ID gives DocumentNotFound instead of InvalidObjectId

### ISSUE THREAD

**Issue by hahuang65** [mongoid/mongoid#3167]
Calling Model.find with an invalidly formatted BSON::ObjectID used to throw a BSON::InvalidObjectId error in Mongoid 2.x

However, in Mongoid 3, it seems it throws a Mongoid::DocumentNotFound error instead of a Moped::BSON::InvalidObjectId error as expected. Is there some sort of option to have it throw the InvalidObjectId error again?

```ruby
id = Moped::BSON::ObjectId.new
 => "51e476877a93d0e9ac00000d"
Player.find(id)
Mongoid::Errors::DocumentNotFound:

Player.find('abc')
Mongoid::Errors::DocumentNotFound:
```

**Comment by durran** [comment]
We need to not raise an exception in the case that @bencrouse mentions.
