### ISSUE TITLE
Model.with(collection: a_collection).where({}) does not use a_collection

### ISSUE THREAD

**Issue by glampr** [mongoid/mongoid#3418]
While ```Model.with(collection: a_collection).find({})``` uses the correct a_collection, using where ```Model.with(collection: a_collection).where({})``` will use the default collection, i.e. "models".

**Comment by arthurnn** [comment]
this should be fixed on latest master, see https://github.com/mongoid/mongoid/issues/3668#issuecomment-74548581 .
thanks
