### ISSUE TITLE
Unable to iterate through a collection without increasing memory usage by an unreasonable amount

### ISSUE THREAD

**Issue by scottmartinnet** [mongoid/mongoid#3536]
We hit an issue where our workers (which read their data from Mongo) are running out of memory.  I've traced this down to the fact that simply reading items from a Mongo collection increases memory usage substantially, even if nothing is done with the data retrieved.

Demonstration code:
```
class Test
  include Mongoid::Document
  store_in collection: "posts" # A collection containing a substantial number of items.
end

before = `ps -o rss= -p #{Process.pid}`.to_i

i = 0
Test.all.each do |item|
  i += 1 # Do nothing with the item.
end; nil

Rails.logger.info "Retrieved #{i} items"

after = `ps -o rss= -p #{Process.pid}`.to_i
difference = after - before
Rails.logger.info "Used #{difference} kb of memory"
```

The output I get for my data:
Retrieved 14018 items
Used 89452 kb of memory

This means that 89 megabytes of memory were used to simply touch each of 14K items, which seems way off.  Unless I'm missing something, this code should be able to iterate through any number of items without using any additional memory beyond the memory to hold a single item.

I'm running the latest version of Mongoid (from commit 5b0f031992cbec66d68c6cb288a4edb952ed5336).  As far as I can tell, literally nothing else is involved in this code.  I keep thinking I must be missing something here, but I have eliminated every factor I can think of and all that remains is Mongoid.

**Comment by durran** [comment]
If you iterate over an entire collection, every document in the collection is going to get loaded, whether you do anything with it or not. Even without Mongoid, by iterating over the cursor everything is going to get deserialized into BSON and still cause memory to gradually increase until the iteration is complete when things can get garbage collected. Quite simply, if you have a huge collection, you should iterate over it in batches so the garbage collector can do its work in between the batches.
