### ISSUE TITLE
Mongoid Criteria unexpected results when searching a document by id

### ISSUE THREAD

**Issue by icortex** [mongoid/mongoid#3578]
mongoid (4.0.0.beta1), rails (4.0.1), ruby (2.1.0), mongoDB (2.4.9)

I have a Mongoid Criteria of `users` and I want to find a user. Given a `user` that I'm sure doesn't exists in the criteria:

    >> users.where(email: user.email).exists?
    => false
    
    >> users.map(&:id).include?(user.id)
    => false

When I search by `id` I always get the user instead of nil:

    >> users.find(user.id)
    => #<User _id: 521a43b37
    
    >> users.where(id: user.id).first
    => #<User _id: 521a43b37
    
    >> users.where(_id: user.id).first
    => #<User _id: 521a43b37
    
    >> users.where(id: user.id).exists?
    => true

Am I doing something wrong?

**Comment by kuldeepaggarwal** [comment]
I think, I should rephrase the problem. It's something like using `where` clause with `:id` options.

e.g
```ruby
user  = User.create! name:'kuldeep', age: 10
user2 = User.create! name:'arthurnn', age: 10


User.where(id: user.id).where(id: user2.id) # Mongoid::Criteria with selector having id = user2.id
```

so the question arises, what should happen?

**Comment by kuldeepaggarwal** [comment]
Somewhat similar to #4002 .

**Comment by durran** [comment]
Closing as we have a more descriptive #4002
