### ISSUE TITLE
Mongoid::Document with field named "err" throwing strange exceptions

### ISSUE THREAD

**Issue by brewboy** [mongoid/mongoid#3615]
Naming a field "err", as shown in the example below, causes an exception to get thrown with the contents of the field as the exception message when retrieving the document from mongo.  This caused fishy behavior because there wasn't actually anything wrong with the query and the error message was not an error message, but it was still throwing.

field :err, type: Array

**Comment by durran** [comment]
Documents with the following field names will cause issues as they will be treated as having errors when retrieved from the database: `err`, `$err`, `error`, `$error`, `errmsg`, `writeConcernErrors`. Please rename the field to avoid these cases.

**Comment by brewboy** [comment]
You might consider a naming convention, one that has less intersection with the scope of user defined fields (e.g. __err).  The way it sits now users have to have a knowledge of the inner-workings of the database.  This ate quite a bit of time debugging, and I imagine it will bite many more if it is not changed.  I still consider this a bug and a bad user experience.
