### ISSUE TITLE
Can't canonicalize query: BadValue unknown operator: $oid

### ISSUE THREAD

**Issue by calebclark** [mongoid/mongoid#3626]
We recently upgraded to MongoDB 2.6 and we're now having errors all over our code base. The main issue relates to $oid queries (see below). I can't find anything on the MongoDB website related to error #17287. Is this a Moped issue?

The operation: #<Moped::Protocol::Query
   @length=103
   @request_id=5
   @response_to=0
   @op_code=2004
   @flags=[:slave_ok]
   @full_collection_name="prd-supercore.organizations"
   @skip=0
   @limit=0
   @selector={"_id"=>{:$oid=>"535d2d75da8da77f44000047"}}
   @fields={"_id"=>1}>
 failed with error 17287: "Can't canonicalize query: BadValue unknown operator: $oid"

**Comment by josevalim** [comment]
@arthurnn any chance we will get this in soon? :)

**Comment by arthurnn** [comment]
@josevalim working on it today!

**Comment by pcreux** [comment]
That's the @josevalim effect. :)
