### ISSUE TITLE
Mongoid 3.1.6: Upgrading to Mongo 2.4.10 causes positional operator error.

### ISSUE THREAD

**Issue by jhoffner** [mongoid/mongoid#3674]
My code works on 2.4.6. However when using version 2.4.10 I get the following errors when calling save on an embedded document.

```
     Moped::Errors::OperationFailure:
       The operation: #<Moped::Protocol::Command
         @length=77
         @request_id=49920
         @response_to=0
         @op_code=2004
         @flags=[]
         @full_collection_name="test.$cmd"
         @skip=0
         @limit=-1
         @selector={:getlasterror=>1, :safe=>true}
         @fields=nil>
       failed with error 16837: "The positional operator did not find the match needed from the query. Unexpanded update: comments.0.comments.$.votes"
```

**Comment by durran** [comment]
Closing as no more info provided. Also see for the core server bug: https://jira.mongodb.org/browse/SERVER-14662

**Comment by jan-hendrik** [comment]
I am having the same issue. What do you need to reproduce it? It's certainly related to models being embedded into other models. With the current version, I am not able to update records anymore.
