### ISSUE TITLE
Safe option concern - save VS create

### ISSUE THREAD

**Issue by glampr** [mongoid/mongoid#3701]
Continued from this #3412 
This works 
```
p = Person.new(name: "Tom")
p.with(write: {w: 0}).save
```
and doesn't trigger the ```getlasterror``` command
but this doesn't
```
Person.with(write: {w: 0}).create!(name: "John")
```
and still triggers the ```getlasterror``` command.

Tested against version 4.0.0

**Comment by arthurnn** [comment]
this should be fixed on latest master, see https://github.com/mongoid/mongoid/issues/3668#issuecomment-74548581 .
thanks
