### ISSUE TITLE
Can't reach to id attribute

### ISSUE THREAD

**Issue by xaph** [mongoid/mongoid#3711]
Hi,

I've a problem to reach the id attribute of my model.

We're using an id column to track our records in traditional way. We're also use _id to reach it from the object.

I want to create an object with different _id and id fields but mongoid uses id as _id. I can read it with read_attribute but write is impossible.

For example:
```
2.0.0p353 :001 > i = Item.last
 => #<Item _id: 528957a99a48ecc1460000fa, id: 122> 
2.0.0p353 :002 > i.id
 => "528957a99a48ecc1460000fa" 
2.0.0p353 :003 > i._id
 => "528957a99a48ecc1460000fa" 
2.0.0p353 :004 > i.read_attribute("id")
 => 122 
2.0.0p353 :005 > i.read_attribute("_id")
 => "528957a99a48ecc1460000fa" 
2.0.0p353 :006 > i.write_attribute("id", 1)
 => 1 
2.0.0p353 :007 > i
 => #<Item _id: 1, id: 122> 
```

How can I set the id attribute?

**Comment by durran** [comment]
Since Mongoid is aliasing `id` to `_id` it is not possible to have both fields in your document and use Mongoid. This is for compatibility with many Rails based things that expect `id` but MongoDB uses `_id`.
