### ISSUE TITLE
[Feature request] Class name aliasing

### ISSUE THREAD

**Issue by muichkine** [mongoid/mongoid#3714]
Hello,

Just as Mongo field names can be aliased to reduce storage space, would it make sense to have a similar way to alias Class names?

I'm asking this because or application growing in size, we've namespaced parts of it. This in turn leads to long class names such as `White::Monkeylearn::SampleTag` that seem to take uneccesary space in db.

**Comment by arthurnn** [comment]
You mean, we we store the class name? like in the `type` field? 
If thats what you mean, you could write some logic on top to handle some mapping look-up.

Or if what you mean is the collection name, you can use the `store_in collection: 'foo'` option to change the collection name.

That said, the first option I dont think we would want to have that on Mongoid TBH.
