### ISSUE TITLE
"assertion 13 not authorized" after MongoDB restart

### ISSUE THREAD

**Issue by heypiotr** [mongoid/mongoid#3719]
Every time I restart out MongoDB server, both the Rails application and the Sidekiq worker I'm using Mongoid with start failing with the following error:

```
A Moped::Errors::QueryFailure occurred in #:

  The operation: #<Moped::Protocol::Query
  @length=98
  @request_id=144
  @response_to=0
  @op_code=2004
  @flags=[]
  @full_collection_name="db.collection"
  @skip=0
  @limit=-1
  @selector={"$query"=>{ ... }, "$orderby"=>{:_id=>1}}
  @fields=nil>
failed with error 13: "not authorized for query on db.collection"
```

Restarting the Rails app and the Sidekiq worker fixes the problem. Any clue?

**Comment by arthurnn** [comment]
Moped solved most of its authentication issues, So I would consider that this is not an issue anymore.
thanks
(let me know if it is still happening on lastest Moped/Mongoid)
