### ISSUE TITLE
Field aliasing is broken in 4.0.0

### ISSUE THREAD

**Issue by kronos** [mongoid/mongoid#3720]
```ruby
class Car
  include Mongoid::Document
end

class Order
  include Mongoid::Document
  field :car, as: :car_info,    type: Hash, :default => {}

  belongs_to :car
end

o = Order.first
o.car_info = {'a' => 'b'}
o.save

o.reload => #<Order _id: 528a5f869f7dcabc50000002, car(car_info): {}, car_id: {"a"=>"b"}>
```

Hash {'a' => 'b'} should be stored inside car hash, not car_id. The code worked well in Mongoid 2.x

**Comment by arthurnn** [comment]
The problem in here is that `field :car, as: :car_info` will create setter/getter for
`car` and `car_info`. And when you define a `belongs_to :car` that will create a `def car=` setter too.

I am pretty much we cannot do much about this. Probably we could throw an error or something so people dont make this mistake. But this type of setup is not recommended.
