### ISSUE TITLE
DocumentNotFound when using reload with store_in

### ISSUE THREAD

**Issue by masone** [mongoid/mongoid#3722]
Given two classes, one of which is using a different database, explicitly defined with `store_in :database => ..`. 

```
class Person
  include Mongoid::Document           
end

class Invite                                                
  include Mongoid::Document                

  store_in :database => 'other'
end  
```

Mongoid 4.0.0 is raising a `Mongoid::Errors::DocumentNotFound` when a reload on `Person` is issued after working with `Invite`.

```
p = Person.create!
p.reload # working

Invite.count # do something with Invite
p.reload # raises Mongoid::Errors::DocumentNotFound      
```

When some method is called on the Person before reloading, everything works fine again.

```
p = Person.create!
Invite.count # do something with Invite
Person.count # do something with Person
p.reload # working again
```

I have set up a demo that illustrates the issue. It includes two tests, one of which is failing. https://github.com/masone/mongoid_reset_demo/tree/master

The tests are failing with 4.0.0, everything is working fine with 3.1.6.

**Comment by danielschlegel** [comment]
Cool, thanks!
