### ISSUE TITLE
Unable to build embedded more than one embedded document of the same type

### ISSUE THREAD

**Issue by wefarrell** [mongoid/mongoid#3724]
After building more than one embedded documents of the same mongoid class, saving the parent document produces the following error:
undefined method `push' for #<Hash:0x0000010436ed68>

Here's a reproduction of the bug:
https://github.com/wefarrell/mongoid-embedded-document-bug

**Comment by durran** [comment]
Closing issue for cleanup as we have the pull request - thanks.
