### ISSUE TITLE
Use same behavior for .find_by when record is not found as in AR

### ISSUE THREAD

**Issue by nicolasblanco** [mongoid/mongoid#3731]
Hello !

Model.find_by method exists in both ActiveRecord and Mongoid but has different behavior when the record in not found.

In Mongoid with the standard configuration, it raises an exception when the document is not found.

In AR, they implemented .find_by which returns nil and .find_by! which throws an exception, see:
http://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-find_by-21

It would be nice and I think not complicated to implement the same feature in Mongoid for homogeneity.

**Comment by arthurnn** [comment]
solved via #3733

thanks

**Comment by PikachuEXE** [comment]
I agree eventually we should provide a bang and a non-bang version for most versions
So we can use both instead of only one.
