### ISSUE TITLE
Bundler error when installing Mongoid

### ISSUE THREAD

**Issue by peterbarnes** [mongoid/mongoid#3734]
I've been trying to use bundler to install Mongoid on my projects and for some reason it has stopped working.  I've used mongoid on so many projects before and for some reason bundler runs into an error when trying to install bson v 2.3.0.  In my gemfile, mongoid is listed as...

` gem "mongoid", github: "mongoid/mongoid" `

or 

` gem "mongoid", "~> 4.0.0" ` (Taken from the [mongoid website](http://mongoid.org/en/mongoid/docs/installation.html))

and both produced the same error.  

I believe the error exists in some incompatibility with the version of bson that mongoid has a dependency with.  Here is the error that occurs after running `bundle install`

`Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/peterbarnes/.rbenv/versions/2.1.0/bin/ruby extconf.rb 
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling native.c
couldn't understand kern.osversion `14.0.0'
native.c:19:23: error: arpa/inet.h: No such file or directory
native.c:20:23: error: sys/types.h: No such file or directory
native.c:23:20: error: stdint.h: No such file or directory
native.c:24:18: error: time.h: No such file or directory
native.c:25:20: error: unistd.h: No such file or directory
In file included from /Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/ruby.h:29,
                 from /Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby.h:33,
                 from native.c:26:
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/defines.h:26:19: error: stdio.h: No such file or directory
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/defines.h:31:23: error: sys/stat.h: No such file or directory
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/defines.h:34:21: error: stdlib.h: No such file or directory
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/defines.h:45:21: error: string.h: No such file or directory
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/defines.h:48:22: error: strings.h: No such file or directory
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/defines.h:51:23: error: inttypes.h: No such file or directory
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/defines.h:61:25: error: sys/select.h: No such file or directory
In file included from /Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/defines.h:68,
                 from /Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/ruby.h:29,
                 from /Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby.h:33,
                 from native.c:26:
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/missing.h:23:45: error: math.h: No such file or directory
In file included from /Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/ruby.h:184,
                 from /Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby.h:33,
                 from native.c:26:
/usr/local/Cellar/apple-gcc42/4.2.1-5666.3/bin/../lib/gcc/i686-apple-darwin11/4.2.1/include/limits.h:10:25: error: limits.h: No such file or directory
In file included from /Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/intern.h:35,
                 from /Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/ruby.h:1694,
                 from /Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby.h:33,
                 from native.c:26:
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/st.h:139: error: expected declaration specifiers or ‘...’ before ‘uint32_t’
In file included from /Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/ruby.h:1694,
                 from /Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby.h:33,
                 from native.c:26:
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/intern.h:348: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘rb_fdset_t’
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/intern.h:440: error: expected declaration specifiers or ‘...’ before ‘fd_set’
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/intern.h:440: error: expected declaration specifiers or ‘...’ before ‘fd_set’
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/intern.h:440: error: expected declaration specifiers or ‘...’ before ‘fd_set’
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/intern.h:440: warning: ‘struct timeval’ declared inside parameter list
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/intern.h:440: warning: its scope is only this definition or declaration, which is probably not what you want
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/intern.h:441: error: expected declaration specifiers or ‘...’ before ‘rb_fdset_t’
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/intern.h:441: error: expected declaration specifiers or ‘...’ before ‘rb_fdset_t’
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/intern.h:441: error: expected declaration specifiers or ‘...’ before ‘rb_fdset_t’
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/intern.h:441: warning: ‘struct timeval’ declared inside parameter list
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/intern.h:442: warning: ‘struct timeval’ declared inside parameter list
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/intern.h:545: error: expected declaration specifiers or ‘...’ before ‘mode_t’
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/intern.h:624: error: expected declaration specifiers or ‘...’ before ‘pid_t’
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/intern.h:638: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘rb_fork’
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/intern.h:639: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘rb_fork_err’
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/intern.h:641: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘rb_waitpid’
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/intern.h:642: error: expected ‘)’ before ‘pid’
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/intern.h:643: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘rb_spawn’
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/intern.h:644: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘rb_spawn_err’
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/intern.h:646: error: expected ‘)’ before ‘pid’
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/intern.h:755: error: expected declaration specifiers or ‘...’ before ‘uint32_t’
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/intern.h:882: error: expected ‘)’ before ‘long’
/Users/peterbarnes/.rbenv/versions/2.1.0/include/ruby-2.1.0/ruby/intern.h:883: error: expected ‘)’ before ‘long’
native.c: In function ‘rb_float_from_bson_double’:
native.c:214: warning: implicit declaration of function ‘memcpy’
native.c:214: warning: incompatible implicit declaration of built-in function ‘memcpy’
native.c: In function ‘rb_object_id_generator_next’:
native.c:236: warning: implicit declaration of function ‘htons’
native.c:236: warning: implicit declaration of function ‘getpid’
native.c:239: warning: implicit declaration of function ‘htonl’
native.c:239: warning: implicit declaration of function ‘time’
native.c:242: warning: implicit declaration of function ‘strlen’
native.c:242: warning: incompatible implicit declaration of built-in function ‘strlen’
native.c:245: warning: incompatible implicit declaration of built-in function ‘memcpy’
native.c: In function ‘rb_integer_is_bson_int32’:
native.c:267: error: nested functions are disabled, use -fnested-functions to re-enable
native.c:267: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘v’
native.c:267: error: ‘v’ undeclared (first use in this function)
native.c:267: error: (Each undeclared identifier is reported only once
native.c:267: error: for each function it appears in.)
native.c: In function ‘rb_integer_to_bson_int32’:
native.c:292: error: nested functions are disabled, use -fnested-functions to re-enable
native.c:292: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘v’
native.c:292: error: ‘v’ undeclared (first use in this function)
native.c: In function ‘rb_integer_to_bson_key’:
native.c:334: error: nested functions are disabled, use -fnested-functions to re-enable
native.c:334: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘v’
native.c:334: error: ‘v’ undeclared (first use in this function)
native.c:338: warning: incompatible implicit declaration of built-in function ‘strlen’
native.c: In function ‘rb_integer_from_bson_int32’:
native.c:358: error: nested functions are disabled, use -fnested-functions to re-enable
native.c:358: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘*’ token
native.c:358: error: ‘v’ undeclared (first use in this function)
native.c:358: error: expected ‘)’ before ‘uint8_t’
native.c:358: warning: type defaults to ‘int’ in declaration of ‘type name’
native.c:358: warning: cast from pointer to integer of different size
native.c:359: error: nested functions are disabled, use -fnested-functions to re-enable
native.c:359: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘integer’
native.c:359: error: ‘integer’ undeclared (first use in this function)
native.c: At top level:
native.c:375: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘rb_bson_to_int64_t’
native.c: In function ‘rb_integer_from_bson_int64’:
native.c:410: warning: implicit declaration of function ‘rb_bson_to_int64_t’
native.c: At top level:
native.c:426: error: expected ‘)’ before ‘v’
native.c: In function ‘rb_integer_to_bson_int64’:
native.c:457: warning: implicit declaration of function ‘int64_t_to_bson’
native.c: In function ‘rb_time_to_bson’:
native.c:477: error: ‘int64_t’ undeclared (first use in this function)
native.c:477: error: expected ‘;’ before ‘t’
native.c:478: error: expected ‘;’ before ‘milliseconds’
native.c:479: error: ‘int32_t’ undeclared (first use in this function)
native.c:479: error: expected ‘;’ before ‘micro’
native.c:480: error: expected ‘;’ before ‘time’
native.c:482: error: ‘time’ undeclared (first use in this function)
native.c: In function ‘rb_time_from_bson’:
native.c:500: error: nested functions are disabled, use -fnested-functions to re-enable
native.c:500: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘millis’
native.c:500: error: ‘millis’ undeclared (first use in this function)
native.c:501: warning: implicit declaration of function ‘rb_time_new’
native.c: In function ‘rb_string_set_int32’:
native.c:521: error: nested functions are disabled, use -fnested-functions to re-enable
native.c:521: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘offset’
native.c:521: error: ‘offset’ undeclared (first use in this function)
native.c:522: error: nested functions are disabled, use -fnested-functions to re-enable
native.c:522: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘v’
native.c:522: error: ‘v’ undeclared (first use in this function)
native.c:532: warning: incompatible implicit declaration of built-in function ‘memcpy’
native.c: In function ‘rb_string_check_for_illegal_characters’:
native.c:548: warning: incompatible implicit declaration of built-in function ‘strlen’
native.c: In function ‘Init_native’:
native.c:603: warning: incompatible implicit declaration of built-in function ‘strlen’
native.c:604: warning: incompatible implicit declaration of built-in function ‘strlen’
native.c:605: warning: incompatible implicit declaration of built-in function ‘strlen’
native.c:606: warning: incompatible implicit declaration of built-in function ‘strlen’
native.c:607: warning: incompatible implicit declaration of built-in function ‘strlen’
native.c:609: warning: incompatible implicit declaration of built-in function ‘strlen’
native.c:611: warning: incompatible implicit declaration of built-in function ‘strlen’
native.c:613: warning: incompatible implicit declaration of built-in function ‘strlen’
native.c:614: warning: incompatible implicit declaration of built-in function ‘strlen’
native.c:615: warning: incompatible implicit declaration of built-in function ‘strlen’
native.c:616: warning: incompatible implicit declaration of built-in function ‘strlen’
native.c:617: warning: incompatible implicit declaration of built-in function ‘strlen’
native.c:618: warning: incompatible implicit declaration of built-in function ‘strlen’
native.c:619: warning: incompatible implicit declaration of built-in function ‘strlen’
native.c:622: warning: implicit declaration of function ‘gethostname’
make: *** [native.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/peterbarnes/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/gems/bson-2.3.0 for inspection.
Results logged to /Users/peterbarnes/.rbenv/versions/2.1.0/lib/ruby/gems/2.1.0/extensions/x86_64-darwin-13/2.1.0-static/bson-2.3.0/gem_make.out
An error occurred while installing bson (2.3.0), and Bundler cannot continue.
Make sure that `gem install bson -v '2.3.0'` succeeds before bundling.`

I am currently running OS X 10.10 Yosemite dev preview.

**Comment by arthurnn** [comment]
@fbernier already gave the solution in the other issue..
thanks
