### ISSUE TITLE
Mongoid doesn't close connection

### ISSUE THREAD

**Issue by reiz** [mongoid/mongoid#3741]
I'm using MongoID 3.1.16 with Rails 3.2.19. Somehow the applications was slower and slower over time. In the Mongo logs I could see that the number of connections went always up, but never down. With each HTTP Request a new connection on MongoDB was opened, but never closed. I added this filter to the ApplicationController and that solved the problem finally. 

```
  after_filter :disconnect_from_mongo

  def disconnect_from_mongo
    Mongoid.default_session.disconnect
  rescue => e
    Rails.logger.error e.message
  end
```

I'm using `config.threadsafe!` in all environments. Not sure if this is a known bug in MongoID 3.1.16, but I guess that's not the normal behavior :-) Maybe I do something wrong?

**Comment by arthurnn** [comment]
On Mongoid 3 + sidekiq, you need to add a `kiqstand` gem. see http://mongoid.org/en/mongoid/v3/tips.html#sidekiq.
But a better solution is moving to mongoid 4.
