### ISSUE TITLE
Mongoid + Grape, ForbiddenAttributesError

### ISSUE THREAD

**Issue by sriv** [mongoid/mongoid#3754]
I noticed the below, am not sure if I am missing something here.

I am building a Grape API (without Rails) and am using Mongoid.

relevant `Gemfile.lock` sections:

    ....
    grape (0.8.0)
      activesupport
      builder
      hashie (>= 2.1.0)
      multi_json (>= 1.3.2)
      multi_xml (>= 0.5.2)
      rack (>= 1.3.0)
      rack-accept
      rack-mount
      virtus (>= 1.0.0)
    ....
    mongoid (4.0.0)
      activemodel (~> 4.0)
      moped (~> 2.0.0)
      origin (~> 2.1)
      tzinfo (>= 0.3.37)
    ....

I have a `has_many` relation defined

    class Person 
        has_many :address
        ....
    end

    class Address
        belongs_to :Person
        ....
    end

I get a bunch of parameters from the Grape endpoint `POST /person/:id/address` and I need to build an address for the Person.

At some point I tried something like this

    person = Person.find(params[:id])
    person.address.create! params

At which point, I got a `ForbiddenAttributesError`. I have encountered this before, and I am aware of Strong Parameters that Rails 4 enforces.

However, I am not using Rails 4, and I notice that Mongoid ha a dependency on ActiveModel (~> 4.0), which is calling the `sanitize_for_mass_assignnment` method, which in turn expects Strong Parameters setup.

Any tips on how I should go about this? As a temporary fix, I have built the Address with selected parameter assignment, and it doesn't look very neat :(

**Comment by arthurnn** [comment]
Mongoid is ActiveModel 4+ , so I would try to upgrade your system.
I will close this, however fell free to submit a isolated failing test to illustrate the problem better if you wish.
