### ISSUE TITLE
Default $orderby _id:1 on where() causing HUGE performance issues

### ISSUE THREAD

**Issue by pkieltyka** [mongoid/mongoid#3768]
On Mongoid 4 / Moped 2 stable, I am seeing crazy performance issues when $orderby: { _id: 1 } is used on a where statement that is doing an $or and looking for a single record. With $orderby its 40 seconds, without it, the same query goes to 1ms.

I checked all of my code and I am not setting a default scope to order by _id anywhere.

**Comment by ixti** [comment]
Running into the same issue. The problem is pretty simple: mongoid adds `$orderBy: { _id: 1 }` when I call `#first` and do not specify `order` myself. When we do somthing like `MyModel.first

**Comment by ixti** [comment]
Running into the same issue. The problem is pretty simple: mongoid adds `$orderBy: { _id: 1 }` when I call `#first` and do not specify `order` myself. When we do somthing like `MyModel.first` that's OK (probably), but when I do some query that uses some index other than `_id_1` that's not OK anymore.

To outline issue, imagine we have a pretty stupid model:

``` ruby
class Sample
  include Mongoid::Document
  field :idx, :type => Fixnum 
  index :idx => 1
end
```

Now, querying `:idx => { :gt => 1_000_000 }` without explicitly specified `sort` will execute following command:

``` javascript
{ $query: { idx: { $gt: 1000000 } }, $orderby: { _id: 1 } }
```

On a fairly large collection this leads into a pretty slow query. Here's some numbers:

``` ruby
# Let's pollute collection with some stuff this will take some time ;))
1_000_000.times.to_a.shuffle.each { |i| Sample.create :idx => i }

# Selector from the above
selector = { :idx => { :$gte => 1_000_000 } }

# Now let's try `#first` without explicit `sort`:
puts Benchmark.measure { Sample.where(selector).first }
# 0.010000   0.000000   0.010000 (  1.230106)

Now the same with explicit `sort`
puts Benchmark.measure { Sample.where(selector).sort(:idx => 1).first }
# 0.000000   0.000000   0.000000 (  0.278825)
```

**Comment by ixti** [comment]
This is monkey-patch I use for Mongoid 3.x:

``` ruby
require "mongoid"

module Mongoid
  module Contextual
    class Mongo
      def with_sorting
        if !criteria.options.key?(:sort) && criteria.selector.empty?
          query.sort(:_id => 1)
        end

        yield
      ensure
        apply_option(:sort)
      end

      def with_inverse_sorting
        if criteria.options.key?(:sort)
          query.sort(Hash[criteria.options[:sort].map { |k, v| [k, -1 * v] }])
        elsif criteria.selector.empty?
          query.sort(:_id => -1)
        end

        yield
      ensure
        apply_option(:sort)
      end
    end
  end
end
```

**Comment by durran** [comment]
We should remove the orderby from `first` and not guarantee the returned order.

**Comment by ixti** [comment]
@durran :bow:
