### ISSUE TITLE
Embed document as hashes rather than arrays

### ISSUE THREAD

**Issue by WagnerMatos** [mongoid/mongoid#3774]
is there a way to make Monogid create embedded documents a hash of hashes instead of an array of hashes?

Basically I'm working on a Rails app that will communicate with Node app and I was trying to mimic the same data structure in the Node app.

Secondarily, I've read it somewhere that is not ideal (for Mongoid) to have documents more than two levels deep. Currently I have three. Is there any issues I should be aware of?

Thanks in advance!

**Comment by durran** [comment]
There's no way for us to create the embedded documents as hashes instead. In this case I would recommend doing it all yourself as the change in Mongoid would be too large to allow this to be customizable.
