### ISSUE TITLE
Scoping documentation appears to be wrong?

### ISSUE THREAD

**Issue by danlo** [mongoid/mongoid#3781]
Greetings,

I did a basic scope following the example @ 

http://mongoid.org/en/mongoid/docs/querying.html#scoping

     scope :english, where(country: "England")

I received a mongoid error stating:

    Mongoid::Errors::InvalidScope:
    Problem:
      Defining a scope of value #<Mongoid::Criteria:0x007ffe956f4488> on XXXXX is not allowed.
    Summary:
      Scopes in Mongoid must be procs that wrap criteria objects.
    Resolution:
      Change the scope to be a proc wrapped critera.

     Example:
       class Band
         include Mongoid::Document
         scope :inactive, ->{ where(active: false) }
       end

The example in the error, indicates that a raw where statement, cannot be used as in the example code in the documentation and must be enclosed in a lambda.

Should the documentation be updated?

-daniel

**Comment by durran** [comment]
Pull request was merged into site.

**Comment by vindia** [comment]
Was it? I can still see it on the current Mongoid.org documentation website. The first two examples still show the incorrect syntax at http://mongoid.org/en/mongoid/docs/querying.html#scoping

    scope :english, where(country: "England")
    scope :rock, where(:genres.in => [ "rock" ])

In [this pull (250)][1] it was fixed correctly, but it is not reflected on the website (yet).

[1]: https://github.com/mongoid/mongoid-site/pull/250/files
