### ISSUE TITLE
ignored rails --environment

### ISSUE THREAD

**Issue by fgarcia** [mongoid/mongoid#3785]
Mongoid ignores the environment set by  `rails --envionment`

    rails c --environment test

With the command above, my `Application.config.mongoid.sessions` shows that the database in use is the development one. However if I set the environment with `RAILS_ENV`:

    RAILS_ENV="test" rails c

The test database is loaded properly

**Comment by durran** [comment]
I cannot replicate this. Here is my output:

```
@memp ➜  echo rvm:(ruby-2.2.0@echo) git:(master) ✗ bundle exec rails c                   
Loading development environment (Rails 4.2.1)
2.2.0 :001 > Echo::Application.config.mongoid.clients
 => {"default"=>{"database"=>"echo_development", "hosts"=>["localhost:27017"], "options"=>nil}} 

@memp ➜  echo rvm:(ruby-2.2.0@echo) git:(master) ✗ bundle exec rails c --environment test
Loading test environment (Rails 4.2.1)
2.2.0 :001 > Echo::Application.config.mongoid.clients
 => {"default"=>{"database"=>"echo_test", "hosts"=>["localhost:27017"], "options"=>{"read"=>{"mode"=>"primary"}, "max_pool_size"=>1}}} 
```

**Comment by durran** [comment]
I'd verify your mongoid.yml is actually different for both envs, that rails says it's loading the correct environment when bringing up the console. Also double check the database name in your config is actually different for development and test.
