### ISSUE TITLE
Id generated on new models

### ISSUE THREAD

**Issue by junhanamaki** [mongoid/mongoid#3787]
Hello.

I've been using mongoid 4.0.0 and when I do MyDocument.new the field _id comes already populated, which doesn't work nice when using rails form helpers (more specifically simple_form), where it generates the path to submit automatically based on id being set or not (I think...).

I tried to set id manually, but now when I save the model it will save it with id nil.

Is there any way to generate the id during save instead of during new?

Thanks.

**Comment by durran** [comment]
Mongoid generates the ids on creation in order for them to be there potentially when associations are added. There is no way around this. You can check `document.persisted?` to know if it is new or not.
