### ISSUE TITLE
Unix domain socket

### ISSUE THREAD

**Issue by Fudoshiki** [mongoid/mongoid#3798]
Can I use connect to mongo via mongodb-27017.sock in mongoid.yml?

http://docs.mongodb.org/manual/reference/connection-string/

MONGO_URI = "mongodb:///tmp/mongodb-27017.sock"

production:
  sessions:
    default:
      uri: <%= ENV['MONGO_URI'] %>

**Comment by Fudoshiki** [comment]
development:
  # Configure available database sessions. (required)
  sessions:
    # Defines the default session. (required)
    default:
      uri: 'mongodb:///tmp/mongodb-27017.sock/torii_development'

rails c 
User.new.save work!

but 

sharevari@MG392:~/repositories/Sekai Bujyutsu Renmei/torii$ rake db:drop --trace
** Invoke db:drop (first_time)
** Invoke db:mongoid:drop (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:mongoid:drop
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/usr/local/rvm/gems/ruby-2.2.0/bundler/gems/mongoid-cd9ad04fe6a2/lib/mongoid/sessions/mongo_uri.rb:25:in `database'
/usr/local/rvm/gems/ruby-2.2.0/bundler/gems/mongoid-cd9ad04fe6a2/lib/mongoid/sessions/mongo_uri.rb:73:in `to_hash'
/usr/local/rvm/gems/ruby-2.2.0/bundler/gems/mongoid-cd9ad04fe6a2/lib/mongoid/sessions/factory.rb:106:in `parse'
/usr/local/rvm/gems/ruby-2.2.0/bundler/gems/mongoid-cd9ad04fe6a2/lib/mongoid/sessions/factory.rb:62:in `create_session'
/usr/local/rvm/gems/ruby-2.2.0/bundler/gems/mongoid-cd9ad04fe6a2/lib/mongoid/sessions/factory.rb:43:in `default'
/usr/local/rvm/gems/ruby-2.2.0/bundler/gems/mongoid-cd9ad04fe6a2/lib/mongoid/sessions.rb:37:in `default'
/usr/local/rvm/gems/ruby-2.2.0/bundler/gems/mongoid-cd9ad04fe6a2/lib/mongoid/tasks/database.rake:23:in `block (3 levels) in <top (required)>'
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:199:in `each'
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/local/rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/usr/local/rvm/rubies/ruby-2.2.0/bin/rake:33:in `<main>'
Tasks: TOP => db:drop => db:mongoid:drop

**Comment by arthurnn** [comment]
So, I did a few tests locally, and definitely Mongoid/Moped dont play nice with unix socket files on the URL I see this as a feature request, and we can push this to mongoid 5, when we use the main 10gen driver again.
cc @durran

**Comment by estolfo** [comment]
@durran, wouldn't this be in 5.0.0?

**Comment by durran** [comment]
We can actually close this as Ruby Driver 2.0 supports unix domain sockets.

**Comment by estolfo** [comment]
I guess that's what I meant; that it would automatically be in 5.0.0
