### ISSUE TITLE
Relations aliasing and specialization

### ISSUE THREAD

**Issue by fusillicode** [mongoid/mongoid#3807]
Is there the possibility to specialize a relation defined in a parent class inside a subclass?

By "specialize" I mean actually to create something like an alias of the parent relation.

I mean, if I have:

```ruby
class Container
  has_many :things, class_name: 'Thing', inverse_of: :container
end

class Thing
  belogs_to :container, class_name: 'Container', inverse_of: :things
end

class SpecificContainer < Container
   # Here I want to specialize the has_many :things relation of Container with a brand new name.
   # At the same time I want to make the parent relation completely inaccessible (in both writing and reading)
end

class SpecificThing < Thing
   # Here I want to specialize the belongs_to :container relation of Thing with a brand new name.
   # At the same time I want to make the parent relation completely inaccessible (in both writing and reading)
end

```

If I'm missing something or if I wasn't clear enough don't hesitate to ask for clarification.

Thanks in advance and sorry for the bother.

**Comment by durran** [comment]
This is not possible via built in functionality of Mongoid, but you could do aliases to the relation name yourself if you wanted. As for not making the parent relation name inaccessible, that is not possible as Mongoid's internals wouldn't be smart enough to figure out the change and use the alias in the subclass.
