### ISSUE TITLE
validation context not working when saving

### ISSUE THREAD

**Issue by anlek** [mongoid/mongoid#3812]
Hey, I'm hitting an odd bug.
Here is my issue:
Given `u` is a user model
```
[32] pry(main)> u.valid?
true
[33] pry(main)> u.save
true
[34] pry(main)> u.valid? :checking_out
false
[35] pry(main)> u.save context: :checking_out
true
```

The `u.save context: :checking_out` should return false and fail.

**Comment by d4rk5eed** [comment]
https://github.com/d4rk5eed/mongoid/blob/3812_validation_context_failed/examples/mongoid_test.rb

You can reproduce bug with .test_default_context and .test_my_context.
It concerns poor documented context feature of activerecord [look](http://api.rubyonrails.org/classes/ActiveRecord/Validations.html)

**Comment by arthurnn** [comment]
should be fixed via https://github.com/mongoid/mongoid/commit/47fbb5fc5e5f3c1baf1c7fd9197c6a5226df6f49
