### ISSUE TITLE
Losing connection to MongoDB randomly in Rails app

### ISSUE THREAD

**Issue by bryanleetc** [mongoid/mongoid#3814]
Been searching for other people who've experienced this issue but it seems I may be the only one. I'm running Rails 4.1.4 + Unicorn, Ruby 2.1.2 and Mongoid 4.0.0. In my production site, I will randomly get connection errors, and the logs hint at something about being unable to connect to MongoDB. 

The site is still accessible, but 3 times out of 10 I will encounter the error. The only way is to restart Unicorn and then the connection issues disappear temporarily until a few hours later.

I suspected it was Unicorn, but I've tried switching to Thin to no avail. I've tried using my own MongoDB deployment and using MongoHQ's hosted databases but that didn't help either. Getting frustrated about this as my current solution is to have the production site restart every 20 minutes! Anyone have any clue what's going on?

**Comment by nofxx** [comment]
You guys could try: https://mms.mongodb.com
Or browser mongodb docs for system configs, page open, nopages, nproc.
I can help with a systemd service: https://gist.github.com/nofxx/b86ec6ce2f6da383e630
