### ISSUE TITLE
does 'autosave' in many to many rel trigger before_save callback?

### ISSUE THREAD

**Issue by jstejada** [mongoid/mongoid#3848]
I was wondering if autosave triggers any save or update callbacks on the referenced document. It seems not to be doing so. Is it expected behavior? e.g.:
 
```ruby
class Product
  include Mongoid::Document
  has_and_belongs_to_many :customers, autosave: true
  before_save :do_stuff

  def do_stuff
    # never called
  end
end

class Customer

  include Mongoid::Document
  has_and_belongs_to_many :products, autosave: true

end

Customer.create! products: [Product.first]
Product.first.customers.count  # => 1
# But it never calls do_stuff
```

Thanks!

**Comment by durran** [comment]
This is because in your example the `Product` is already persisted - Mongoid sees that it has not changed and does not call save on it since it's not dirty to avoid the extra unnecessary database call.

**Comment by jstejada** [comment]
thanks @durran !
