### ISSUE TITLE
rake db:mongoid:create_indexes does not create indexes 

### ISSUE THREAD

**Issue by TheR2** [mongoid/mongoid#3860]
for models defined in gems and loaded from local directory.

Snip from Gemfile:
if ENV['RAILS_ENV'] == 'development' 
  gem 'thin'
  gem 'drg_cms', path: '../drg_cms'
  gem 'drg_default_html_editor', path: '../drg_default_html_editor'
  gem 'register_duo', path: '../register_duo'
  gem 'ppk', path: '../ppk'
  gem 'drg_reports', path: '../drg_reports'
else #PRODUCTION
  gem 'drg_cms' #, '= 0.0.7'
  gem 'drg_default_html_editor' #, '= 0.0.1'
  gem 'register_duo'
  gem 'ppk'
  gem 'drg_reports'
end

But only in development environment. I checked and indexes are created in test and production. 

by
TheR

**Comment by arthurnn** [comment]
As far as I can tell this should be working on master by now.
Let me know if it doesnt.
