### ISSUE TITLE
creating duplicate field in document

### ISSUE THREAD

**Issue by uptownhr** [mongoid/mongoid#3861]
It is currently possible to create a document with duplicate fields. IE

```
{ 
  test: 'asdf',
  test: 'zzzz'
}
```

This is possible by using a symbol or a string key in the hash. IE

```
var data = {
  'test': 'asdf',
  :test: 'zzzz'
}

Test.new(data).save()
```

**Comment by durran** [comment]
No this is not possible. Even in the second circumstance the underlying keys are all converted to strings and the second value would override the first.
