### ISSUE TITLE
Namespaced models named 'Standard' clash with Fields::Standard

### ISSUE THREAD

**Issue by nvloff** [mongoid/mongoid#3865]
Demo app: https://github.com/nvloff/mongoid_standard_model

```ruby
# app/models/project.rb

class Project
  include Mongoid::Document
end

# app/models/project/standard.rb

class Project
  class Standard < Project
  end
end

# test/models/project/standard_test.rb
require 'test_helper'

class Project::StandardTest < ActiveSupport::TestCase
  test 'class' do
    assert_equal 'Project::Standard', Project::Standard.name
  end

  test 'init' do
    assert Project::Standard.new
  end
end
```

```sh
→ rake test
Run options: --seed 61003

# Running:

FE

Finished in 0.004091s, 488.8780 runs/s, 244.4390 assertions/s.

  1) Failure:
Project::StandardTest#test_class [/Users/nvloff/projects/mongoid_standard_model/test/models/project/standard_test.rb:5]:
Expected: "Project::Standard"
  Actual: "Mongoid::Fields::Standard"


  2) Error:
Project::StandardTest#test_init:
ArgumentError: wrong number of arguments (0 for 1)
    test/models/project/standard_test.rb:9:in `new'
    test/models/project/standard_test.rb:9:in `block in <class:StandardTest>'

2 runs, 1 assertions, 1 failures, 1 errors, 0 skips
```

**Comment by durran** [comment]
Once a `Mongoid::Document` is included in your model, you're going to have a name collision with any Mongoid namespaced class that is included and will need to change the name of your class. It's just one of the many drawbacks when breaking functionality into modules with an Active Record pattern. We could change names of our modules to really odd things so they wouldn't clash, but then those looking at the source would haveno idea how it is organized.

**Comment by nvloff** [comment]
@durran sure that sounds quite reasonable. The exact issue here was an undocumented breaking change from mongoid 2. Where a naming(Standard) worked great on mongoid2 it just breaks with strange errors in mongoid4.

**Comment by durran** [comment]
Understandable. I don't suspect going forward that the modules will have such drastic name changes anymore. From Mongoid 2 to Mongoid 4 there was quite a refactoring.
