### ISSUE TITLE
Cannot have "attributes" as a relation name

### ISSUE THREAD

**Issue by yudho** [mongoid/mongoid#3880]
I have a model named "Blob" as shown below
```ruby
class Blob
  include Mongoid::Document
  field :name, type: String
  embeds_many :attributes, class_name: "BlobAttribute"
  accepts_nested_attributes_for :attributes
end
```
and model named "BlobAttribute" below
```ruby
class BlobAttribute
  include Mongoid::Document
  field :name, type: String
  embedded_in :blob, inverse_of: :attributes
end
```

On page load (on loading of BlobAttribute class in development mode), I get a "System Stack too Deep" error.
When I change the name of the relation to be "blob_attributes" instead, it worked. 

I suspect that there is a method named "attributes" that overlap with the relation so that we cannot have a relation named "attributes". I am on Mongoid 4.0.0

**Comment by durran** [comment]
`attributes` is a reserved word in Mongoid as you would be overriding Mongoid's `attributes` method by defining a relation with this name. It's just simply not allowed in this case.
