### ISSUE TITLE
set gives NoMethodError for non existing field instead of Mongoid::Errors::UnknownAttribute

### ISSUE THREAD

**Issue by Shwetakale** [mongoid/mongoid#3888]
My Game model is -

    class Game
      include Mongoid::Document
      field :name
    end

When i am trying to set value of non existing field 

    Game.last.set(no_of_players: 11)

It gives 'NoMethodError'

    NoMethodError: undefined method `no_of_players=' for #<Game _id: 548fcea67368776fcf010000, name: nil>
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/mongoid-4.0.0/lib/mongoid/persistable/settable.rb:25:in `block (2 levels) in set'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/mongoid-4.0.0/lib/mongoid/persistable.rb:172:in `block in process_atomic_operations'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/mongoid-4.0.0/lib/mongoid/persistable.rb:167:in `each'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/mongoid-4.0.0/lib/mongoid/persistable.rb:167:in `process_atomic_operations'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/mongoid-4.0.0/lib/mongoid/persistable/settable.rb:24:in `block in set'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/mongoid-4.0.0/lib/mongoid/persistable.rb:145:in `prepare_atomic_operation'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/mongoid-4.0.0/lib/mongoid/persistable/settable.rb:23:in `set'
	from (irb):5
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/railties-4.1.1/lib/rails/commands/console.rb:90:in `start'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/railties-4.1.1/lib/rails/commands/console.rb:9:in `start'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/railties-4.1.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

And when i am trying to use update_attributes

    Game.last.update_attributes(no_of_players: 11)

It give 'Mongoid::Errors::UnknownAttribute'

    Mongoid::Errors::UnknownAttribute: 
    Problem:
     Attempted to set a value for 'no_of_players' which is not allowed on the model Game.
    Summary:
     Without including Mongoid::Attributes::Dynamic in your model and the attribute does not already exist in the attributes hash, attempting to call Game#no_of_players= for it is not allowed. This is also triggered by passing the attribute to any method that accepts an attributes hash, and is raised instead of getting a NoMethodError.
    Resolution:
    You can include Mongoid::Attributes::Dynamic if you expect to be writing values for undefined fields often.
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/mongoid-4.0.0/lib/mongoid/attributes/processing.rb:96:in `process_attribute'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/mongoid-4.0.0/lib/mongoid/attributes/processing.rb:25:in `block in process_attributes'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/mongoid-4.0.0/lib/mongoid/attributes/processing.rb:23:in `each_pair'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/mongoid-4.0.0/lib/mongoid/attributes/processing.rb:23:in `process_attributes'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/mongoid-4.0.0/lib/mongoid/attributes.rb:203:in `block in assign_attributes'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/mongoid-4.0.0/lib/mongoid/threaded/lifecycle.rb:26:in `_assigning'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/mongoid-4.0.0/lib/mongoid/attributes.rb:202:in `assign_attributes'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/mongoid-4.0.0/lib/mongoid/persistable/updatable.rb:51:in `update'
	from (irb):6
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/railties-4.1.1/lib/rails/commands/console.rb:90:in `start'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/railties-4.1.1/lib/rails/commands/console.rb:9:in `start'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/railties-4.1.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
  

isn't this set should behave like?

**Comment by arthurnn** [comment]
fixed by https://github.com/mongoid/mongoid/commit/35aea60b285afce7a1d1f22602b14b21e91c08fa
