### ISSUE TITLE
set doesn't allow to set value of non existing field when included Mongoid::Attributes::Dynamic

### ISSUE THREAD

**Issue by Shwetakale** [mongoid/mongoid#3889]
My Game model is -

    class Game
       include Mongoid::Document
       include Mongoid::Attributes::Dynamic
       field :name, type: String
    end

Here i have included Attributes::Dynamic and when i try to set value of non existing field

    Game.last.set(no_of_players: 11)

It gives NoMethodError

    NoMethodError: undefined method `no_of_players=' for #<Game _id: 548fcea67368776fcf010000, name: nil>
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/mongoid-4.0.0/lib/mongoid/attributes/dynamic.rb:136:in `method_missing'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/mongoid-4.0.0/lib/mongoid/persistable/settable.rb:25:in `block (2 levels) in set'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/mongoid-4.0.0/lib/mongoid/persistable.rb:172:in `block in process_atomic_operations'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/mongoid-4.0.0/lib/mongoid/persistable.rb:167:in `each'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/mongoid-4.0.0/lib/mongoid/persistable.rb:167:in `process_atomic_operations'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/mongoid-4.0.0/lib/mongoid/persistable/settable.rb:24:in `block in set'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/mongoid-4.0.0/lib/mongoid/persistable.rb:145:in `prepare_atomic_operation'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/mongoid-4.0.0/lib/mongoid/persistable/settable.rb:23:in `set'
	from (irb):1
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/railties-4.1.1/lib/rails/commands/console.rb:90:in `start'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/railties-4.1.1/lib/rails/commands/console.rb:9:in `start'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/railties-4.1.1/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /home/shweta/.rvm/gems/ruby-2.1.0/gems/railties-4.1.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

And when i call update_attributes
  
    Game.last.update_attributes(no_of_players: 11)
     => true 

It works fine.

As we have included 'Mongoid::Attributes::Dynamic' it should allow us to set value of non existing field just like 'update_attributes' allows. Isn't it?

**Comment by arthurnn** [comment]
fixed by https://github.com/mongoid/mongoid/commit/35aea60b285afce7a1d1f22602b14b21e91c08fa
