### ISSUE TITLE
Timeout connecting to primary node in replica set did not log an error

### ISSUE THREAD

**Issue by bitGnome** [mongoid/mongoid#3891]
Not sure if there is a setting that we need in our mongoid config but we recently had an issue where there was a typo setting the mongo port in our replica set. primary node had 27019 instead of 27017, the secondary had the correct port. 

We did not see any errors in our Rails log regarding the timeout to the primary. Is there a config setting that we can turn on to log this? Any insight or help will be greatly appreciated. Thanks!

**Comment by durran** [comment]
This will be logged now on master (5.0.0) with the new driver.
