### ISSUE TITLE
Secondary node failed and webservers became slow

### ISSUE THREAD

**Issue by johnnyshields** [mongoid/mongoid#3892]
Using Mongoid version 3.1. I had a random secondary db instance failure, and noticed that my webservers became quite slow trying to connect to it but repeated failing. When I removed the dead instance from my `mongoid.yml` and bounced the webserver process, the issues was resolved. I wonder if there's a way to make Mongoid a bit more resilient here, such as not attempting to connect to a secondary node for a given timeout (say 30 minutes) after a series of failures?

**Comment by arthurnn** [comment]
Mongoid does not handle connections to MongoDB.
Moped is the mongodb driver Mongoid uses to connect to db. This bug belongs there. And there is some work happening there already to make it more resilient. Feel free to browser through the commits on https://github.com/mongoid/moped/commits and issues to see if someone else already report this issue..

cheers.
