### ISSUE TITLE
rake tasks don't work with uri

### ISSUE THREAD

**Issue by Fudoshiki** [mongoid/mongoid#3905]
development:
  sessions:
    default:
      uri: 'mongodb:///tmp/mongodb-27017.sock/db_development'

Working pretty nice with mongoid master and mongodb 2.7.8, but rake tasks unknow how work via uri

$ rake db:drop
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/usr/local/rvm/gems/ruby-2.2.0/bundler/gems/mongoid-cd9ad04fe6a2/lib/mongoid/sessions/mongo_uri.rb:25:in `database'
/usr/local/rvm/gems/ruby-2.2.0/bundler/gems/mongoid-cd9ad04fe6a2/lib/mongoid/sessions/mongo_uri.rb:73:in `to_hash'
/usr/local/rvm/gems/ruby-2.2.0/bundler/gems/mongoid-cd9ad04fe6a2/lib/mongoid/sessions/factory.rb:106:in `parse'
/usr/local/rvm/gems/ruby-2.2.0/bundler/gems/mongoid-cd9ad04fe6a2/lib/mongoid/sessions/factory.rb:62:in `create_session'
/usr/local/rvm/gems/ruby-2.2.0/bundler/gems/mongoid-cd9ad04fe6a2/lib/mongoid/sessions/factory.rb:43:in `default'
/usr/local/rvm/gems/ruby-2.2.0/bundler/gems/mongoid-cd9ad04fe6a2/lib/mongoid/sessions.rb:37:in `default'
/usr/local/rvm/gems/ruby-2.2.0/bundler/gems/mongoid-cd9ad04fe6a2/lib/mongoid/tasks/database.rake:23:in `block (3 levels) in <top (required)>'
Tasks: TOP => db:drop => db:mongoid:drop
(See full trace by running task with --trace)

**Comment by Fudoshiki** [comment]
https://github.com/mongoid/mongoid/issues/3798

**Comment by arthurnn** [comment]
I will close this as #3798 is a dup pretty much.
