### ISSUE TITLE
Simple sum(:key_name) query is slow due to gathering of (needless) extra stats

### ISSUE THREAD

**Issue by themasterchef** [mongoid/mongoid#3910]
When executing a simple `sum(:key_name)`query, it appears that Mongoid's query generator decides to obtain a bunch of other aggregate statistics about the collection. The output of Moped for this query is:

```
MOPED: 127.0.0.1:27017 COMMAND      database=[my db] command={:aggregate=>"[my collection]", :pipeline=>[{"$match"=>{"key_name"=>{"$nin"=>[nil]}}}, {"$group"=>{"_id"=>"key_name", "count"=>{"$sum"=>1}, "max"=>{"$max"=>"$key_name"}, "min"=>{"$min"=>"$key_name"}, "sum"=>{"$sum"=>"$key_name"}, "avg"=>{"$avg"=>"$key_name"}}}]}
```

When I write the query by hand, and don't include the count, max, min, avg, or nin bits (ie just cut the query down to sum), the time to run the query drops by 1/3.

Is there a reason that all these extra stats are gathered during the aggregation, or can Mongoid be safely altered to not do this?

(Using Mongoid 4.0.0)

**Comment by durran** [comment]
Mongoid's aggregation is just a simple helper and is the kitchen sink really... If you want more control you'll need to drop down to the driver level.
