### ISSUE TITLE
Issues with ruby 2.2.0

### ISSUE THREAD

**Issue by Chocksy** [mongoid/mongoid#3915]
I tried to update my app to ruby 2.2.0 and it seems the Timestamps has an issue but i'm not sure how right now. 

I get this error when a new model is saved:
```
Mongoid::Errors::UnknownAttribute: 
Problem: Attempted to set a value for 'updated_at' which is not allowed on the model 
ParsedItem.Summary: Without including Mongoid::Attributes::Dynamic in your model and the attribute 
does not already exist in the attributes hash, attempting to call ParsedItem#updated_at= for it is not 
allowed. This is also triggered by passing the attribute to any method that accepts an attributes hash, and 
is raised instead of getting a NoMethodError.Resolution: You can include Mongoid::Attributes::Dynamic if 
you expect to be writing values for undefined fields often.
```

So when it's trying to save the updated_at field i get that it does not exist.

Also after i removed the timestamps it gave me the same issue with a regular field called desc...

**Comment by amw** [comment]
Running ruby 2.2 here and everything seems normal. No issues like the one you've mentioned. I think you need to look somewhere else. If you still believe this to be Mongoid issue try to provide minimum working example that showcases this bug.

**Comment by Chocksy** [comment]
Thanks @amw for the reply. What happened is that right after i downgraded ruby back from 2.2.0 everything started working again with rails 4.2.0. Downgrading rails was not a solution so that's how i got to this conclusion. I'm not able to make a test right now maybe it was something else. I'll close this issue and get back in case i find other details.

**Comment by arthurnn** [comment]
indeed, travis is running green on ruby 2.2 , so mongoid side should be fine.
