### ISSUE TITLE
How can I upload my translation

### ISSUE THREAD

**Issue by arthurtalkgoal** [mongoid/mongoid#3918]
Hi,

I found there is no translation for Chinese.
zh-TW.mongoid.errors.messages.validations.message

I wanna upload my translation, but there is only one en.yml in the locales, can I ask where should I upload? Or I just push to the config/locales folder?

**Comment by simi** [comment]
Yes, just copy them into locales directory. You can use [this](https://github.com/mongoid/mongoid/blob/master/lib/config/locales/en.yml) as base.
