### ISSUE TITLE
Comparable class warnings / deprecations while running specs.

### ISSUE THREAD

**Issue by RickCarlino** [mongoid/mongoid#3928]
I recently upgraded to 4.0.1 and noticed some warnings when I run my test suite:
```
lib/mongoid/attributes.rb:175: warning: Comparable#== will no more rescue exceptions of #<=> in the next release.
lib/mongoid/attributes.rb:175: warning: Return nil in #<=> if the comparison is inappropriate or avoid such comparison.
lib/mongoid/changeable.rb:188: warning: Comparable#== will no more rescue exceptions of #<=> in the next release.
lib/mongoid/changeable.rb:188: warning: Return nil in #<=> if the comparison is inappropriate or avoid such comparison.
lib/mongoid/changeable.rb:188: warning: Comparable#== will no more rescue exceptions of #<=> in the next release.
lib/mongoid/changeable.rb:188: warning: Return nil in #<=> if the comparison is inappropriate or avoid such comparison.
lib/mongoid/changeable.rb:188: warning: Comparable#== will no more rescue exceptions of #<=> in the next release.
lib/mongoid/changeable.rb:188: warning: Return nil in #<=> if the comparison is inappropriate or avoid such comparison.
```
This also seems to be happening when I downgraded to 4.0.0.

Is there anything I should avoid or change on my end that would make the warnings go away?

The offending code can be found [here](https://github.com/openfarmcc/OpenFarm/pull/471)

**Comment by simonv3** [comment]
I've tracked this down in the openfarm code to specifically (at least partially) here:

```
@existing_crop.pictures.find(do_delete).map(&:destroy)
```
Here: https://github.com/openfarmcc/OpenFarm/blob/master/app/mutations/crops/crops_concern.rb#L43

**Comment by arthurnn** [comment]
thanks @simonv3 . So as far as I can tell this is not a bug on Mongoid.

**Comment by simonv3** [comment]
@arthurnn there is nothing wrong with that code though as far as I can tell. It's doing a find on an array of mongoid ids, and then doing a destroy on all of them. 

What is it about that that would cause that warning?

**Comment by simonv3** [comment]
@arthurnn @durran I would really appreciate a second look at this.
