### ISSUE TITLE
Polymorphic document are instantiated from _type attribute, cannot prefix with module name

### ISSUE THREAD

**Issue by bmedici** [mongoid/mongoid#3929]
My application uses some SCI documents with inheritance, then they are saved with a _type attribute to remember the Object class name.
Whe the same database if accessed from another application, the name of the corresponding class may be prefixed with different module names (typically the application or scope name), and document instatiation won't work.

Example in application1

    class StepStart < Step
    end

When saved, this document has attribute _type="StepStart"

Example in application2

    module App2
        class StepStart < Step
        end
    end

The document I retrieve there still has _type="StepStart", I wish I could tell on the relation that objects read should be looked up with the current document module (current context, App2 in the example).
Another option would be just to pass a lambda used to compute the class name from the _type field, which would affect how Factory.build uses the "klass" parameter to instantiate the object.

Another suggestion on how to solve this ?
Thanks !

**Comment by muichkine** [comment]
That is definitely something on your side. :) Mismatching class names in different applications using the same data is a dangerous sport. That also means that in app 2 if you save StepStart, it will be prefixed with the namespace and be un-instantiatable in app 1.

Now, what you could do, beside inserting your own logic into mongoid (looking for _type in the code and patching on your fork), you could simply add in app 2

StepStart = App2::StepStart

which *should* work but is worth trying anyway. :)

**Comment by arthurnn** [comment]
I like @muichkine suggesting. Thanks!

This is not a issue on Mongoid side then.
