### ISSUE TITLE
Query find_by adds a sort _id

### ISSUE THREAD

**Issue by chenkirk** [mongoid/mongoid#3934]
I've noticed mongoid automatically adds a `$orderby"=>{:_id=>1}` to find_by query.

For example, `User.find_by(:email => 'some@email.com')` does the following query
    users selector={"$query"=>{"email"=>"kirk@grantoo.org"}, "$orderby"=>{:_id=>1}} flags=[] limit=-1 skip=0 batch_size=nil fields=nil runtime: 0.8535ms

This is pretty taxing on a large production database. Because of the extra sort, there would need to be a multi-key index of {:email => 1, :_id => 1} instead of just {:email => 1}.

In our case, that's an extra 800MB of ram required to store the extra :_id sorting.

The current workaround I have is to specify a mock sort. For example, I'd do `User.order_by(:email.asc).find_by(:email => 'some@email.com')`

**Comment by arthurnn** [comment]
thanks for reporting this.
Fixed on master, should be on 4.0.2

**Comment by jeremyhaile** [comment]
@arthurnn Shouldn't this be used for `.first` and `.last` - it seems those also add the sort parameter which results in the same problem.

**Comment by arthurnn** [comment]
But to get the `first` and `last` value you need a sort. As, on `find_by`, you just want one record back.

**Comment by deXterbed** [comment]
For some reason, Devise isn't using find_by while authenticating users. They are using where. Irrelevant i  know, but i thought i should put it here.

**Comment by jeremyhaile** [comment]
As a user, I am surprised by the difference in behavior between `find_by` and `where(...).first`.  I wouldn't expect either of these to add a sort to my query.  It's possible that my `first` query needs a sort, but if it's unique, it may not need a sort. And if I call first without a sort, it's my fault.

#3934 fixes the problem of adding a sort to `find_by` (which I am grateful for) but this makes `Model.find_by(...)` different from `Model.where(...).first`

ActiveRecord appears to have the same behavior, but in my experience most RDBMS are smarter about applying indexes and will realize that they do not need to use the _id index if the other condition is on a unique index, for example. Unfortunately, this does not seem to be the case for MongoDB, as I've seen adding an _id sort increase the query time exponentially.

The fact that the ORM layer adds this sort, resulting in an exponentially higher query time, and in a transparent/unexpected way seems bad to me.

Of course, for unique columns, you can work around this problem by calling `find_by` - but if you are using a 3rd party library like @deXterbed pointed out with Devise, you may end up with unexpected performance problems.

**Comment by arthurnn** [comment]
@jeremyhaile valid point. Keep in mind, that first needs to have an order, because 90% of the cases you are calling first and not using a uniq index. It is hard for Mongoid to know.
IMO, this is more a responsibility of who is using Mongoid, and if you know that `.first` will return only one result you would use `find_by` instead, which I fixed that problem in there.

Fell free to open a PR, if you can think a better way to solve this 10% use case for `first` that can remove the order because the index is uniq.
