### ISSUE TITLE
before_save & before_update callbacks don't work with set method

### ISSUE THREAD

**Issue by Azzurrio** [mongoid/mongoid#3943]
When I try to update an attribute using `set` method like `User.last.set email: "user@example.com"` It actually updates the record in the DB but `before_update` & `before_save` callbacks don't work. What's the problem there?

**Comment by deXterbed** [comment]
they won't work with set

**Comment by arthurnn** [comment]
`set` operation is an atomic operation.
from http://mongoid.org/en/mongoid/docs/persistence.html#atomic
> When executing atomic operations via these methods, no callbacks will ever get run, nor will any validations.
