### ISSUE TITLE
Accessing the field by square bracket operator + Custom field serialization

### ISSUE THREAD

**Issue by Romey** [mongoid/mongoid#3945]
When I access field with custom serialization by square bracket operator or read_attribute method, I get raw value. Is it a bug? Example:

```ruby
class Record
  include Mongoid::Document
  field :test, type: TreeValue
end
```
```ruby
  record.test # <TreeValue:0x007f9e47034c78>
  record[:test] # Array (2 elements)
  record.read_attribute(:test) # Array (2 elements)
```

Mongoid v4.0.1

**Comment by arthurnn** [comment]
Not 100% if it is a bug or not, TBH.
Can you write a reproducible script so I can simulate this?
You can use https://github.com/mongoid/mongoid/blob/master/examples/mongoid_test.rb as a base.

**Comment by durran** [comment]
`read_attribute` always gets the raw value, the getter method is the one that will get the custom serialized value.
