### ISSUE TITLE
Question: How to run native Javascript code on MongoDB?

### ISSUE THREAD

**Issue by johnnyshields** [mongoid/mongoid#3947]
Hi, I'd like to be able to natively execute Javascript code on MongoDB via Mongoid / Moped

Here's a simplified example of what I'd like to do:
```
var cursor = #{ criteria.query.xxx ? }
if (cursor.count < 100) { cursor } else { [] }
```

* `criteria.query.xxx` represents the serialized Javascript string for my Mongoid query criteria which I've passed-in via string interpolation, i.e `db.customers.find({"name": "bob"})`.
* The result should be serialized into `Customer` objects in Ruby.

Is this possible to do? (I'm using Mongoid 3 at the moment)

**Comment by durran** [comment]
If you pass a `String` to `#where` on a `Criteria` then the string will be assumed to be javascript code to execute and will perform a $where on the server. That's the only entry point to do it from Mongoid.

```ruby
Customer.where("javascript code here")
```
