### ISSUE TITLE
Collision in active_support concern class_methods

### ISSUE THREAD

**Issue by akicho8** [mongoid/mongoid#3951]
C.f should be "ok". But when have require the mongoid, the result is xxx. mongoid and activesupport I do not know either side of the issue. Please tell me if there is a workaround.

```ruby
gem "psych", "2.0.12"
require "psych"

gem "activesupport", "4.2.0"
require "active_support/core_ext/kernel/concern"

gem "mongoid", "4.0.1"
require "mongoid" if true       # <-- If false the result is ok

class B
  def self.f
    "xxx"
  end
end

concern :M do
  class_methods do
    self                        # => Mongoid::Extensions::Object::ClassMethods
    def f
      "ok"
    end
  end
end

class C < B
  include M
end

C.f                             # => "xxx"
```

**Comment by akicho8** [comment]
M module, and in this way to write, why, the C.f result is ok.
```ruby
module M
  extend ActiveSupport::Concern
  module ClassMethods
    def f
      "ok"
    end
  end
end
```

**Comment by arthurnn** [comment]
Thanks for submitting the ticket, do you mind creating a unit test to illustrate the issue better? 
thanks

**Comment by akicho8** [comment]
Cause I've found.

When define a instance methods, defined unnecessary ClassMethod module.

https://github.com/mongoid/mongoid/blob/master/lib/mongoid/extensions/object.rb#L273
https://github.com/mongoid/origin/blob/master/lib/origin/extensions/object.rb#L201

Code of current situation.

```ruby
module M
  def a; end
  module ClassMethods
    def b; end
  end
end

Object.include M                # Define unnecessary Object::ClassMethods
Object.extend M::ClassMethods

defined? Object::ClassMethods   # => "constant"
```

It does not conflict to have become as follows.

```ruby
module M
  module InstanceMethods
    def a; end
  end
  module ClassMethods
    def b; end
  end
end

Object.include M::InstanceMethods
Object.extend M::ClassMethods

defined? Object::ClassMethods   # => nil
```

**Comment by akicho8** [comment]
https://github.com/akicho8/test_mongoid/blob/master/test.rb
Confirmed to operate normally by deleting Object::ClassMethods.

**Comment by akicho8** [comment]
And tests to reproduce the bug, I wrote the code to fix the bug.
Could you please confirm.:smile:

**Comment by akicho8** [comment]
https://github.com/rails/rails/pull/20494
