### ISSUE TITLE
authenticationDatabase option in mongoid.yml

### ISSUE THREAD

**Issue by deXterbed** [mongoid/mongoid#3953]
Is there a way to pass the --authenticationDatabase option to mongodb through mongoid.yml?

**Comment by deXterbed** [comment]
@arthurnn can i create a pull request for this?

**Comment by arthurnn** [comment]
@deXterbed for sure,! :heart:

**Comment by topac** [comment]
+1

**Comment by durran** [comment]
This is `auth_source` in the options in 5.0.0.
