### ISSUE TITLE
NoMethodError: undefined method `unit_of_work' for Mongoid:Module

### ISSUE THREAD

**Issue by sselvamani22** [mongoid/mongoid#3954]
I am using mongoid 4.0.0 on rails 4.2.0 aplication, when I use `unit_of_work` it throws an `NoMethodError: undefined method unit_of_work for Mongoid:Module`. It seems it was removed here https://github.com/mongoid/mongoid/pull/3457. So what will be the alternate solution to use `unit_of_work` method.

**Comment by arthurnn** [comment]
`unit_of_work` is not necessary anymore, we have a proper eager_load framework now, and a query cache.

The query cache could be enabled by adding:
```
config.middleware.use(Mongoid::QueryCache::Middleware)
```

**Comment by sselvamani22** [comment]
Thanks for your info. Kindly mention above changes into `CHANGELOG.md` file.
