### ISSUE TITLE
Unable to create indexes for specified database

### ISSUE THREAD

**Issue by hackeron** [mongoid/mongoid#3965]
Hi there,

I have a multi-tier application that does a before_filter :switch_database - so every subdomain is switched to a different database using Mongoid.override_database(database_name)

This is all working beautifully, but I cannot programatically get mongoid to generate indexes on database creation, I tried this:

```
# rake db:mongoid:create_indexes RAILS_ENV=production DATABASE=timeline_maryrose_production
I, [2015-02-25T23:38:32.050239 #3292]  INFO -- : MONGOID: Created indexes on Item:
I, [2015-02-25T23:38:32.050370 #3292]  INFO -- : MONGOID: Index: {:event_id=>1}, Options: {:background=>true}
I, [2015-02-25T23:38:32.050423 #3292]  INFO -- : MONGOID: Index: {:path=>1}, Options: {}
```

However when I check if an index is created, I see this:

```
$ mongo timeline_maryrose_production
MongoDB shell version: 2.4.12
connecting to: timeline_maryrose_production
> db.system.indexes.find()
{ "v" : 1, "name" : "_id_", "key" : { "_id" : 1 }, "ns" : "timeline_maryrose_production.items" }
```

Is there anyway to generate indexes from within my ruby code or at least specify an environment variable to generate indexes for a specific database?

**Comment by hackeron** [comment]
Ah, I found a way, like this:

```ruby
    Mongoid.override_database(database_name)
    Mongoid::Tasks::Database.create_indexes # Make sure indexes exist
```

Is there anyway to have missing indexes automatically created out of box? - or a recommended way to achieve this?

**Comment by durran** [comment]
We will not add the ability to create missing indexes automatically as it's too risky of a feature and more often than not a bad practice (For example a production deploy with a large dataset and indexes not setto background would block). You will have to create them programatically directly via the underlying driver or use the rake task.

**Comment by hackeron** [comment]
I have a multi tier app, so every subdomain is a different database that is created dynamically when a user registers. Creating the indexes programatically or via a rake task is not an option :( - if this is risky, then it can be explicitly set as a preference option?
