### ISSUE TITLE
delete_if not working correctly on embedded documents (skips documents)

### ISSUE THREAD

**Issue by knovoselic** [mongoid/mongoid#3966]
It seems that delete_if doesn't check all embedded documents. Consider this minimal example:

    class BugTest
      include Mongoid::Document

      embeds_many :children
    end

    class Child
      include Mongoid::Document

      embedded_in :bug_test

      field :value, type: Integer
      field :index, type: Integer

      def to_s
        "#{value}, #{index}"
      end
    end

    Moped.logger = nil
    x = BugTest.new
    4.times { |i| x.children << Child.new(value: 0, index: i)}
    2.times { |i| x.children << Child.new(value: 1, index: i + 4)}
    x.save
    puts 'Embedded documents before calling delete_if:'
    puts x.children
    x.children.delete_if {|x| x.value == 0}
    puts 'Embedded documents after calling delete_if:'
    x.save
    puts x.children

This is the output from the script:

    Embedded documents before calling delete_if:
    0, 0
    0, 1
    0, 2
    0, 3
    1, 4
    1, 5
    Embedded documents after calling delete_if:
    0, 1
    0, 3
    1, 4
    1, 5

As you can see, only two out of four documents which have value == 0 were removed. It seems that delete_if removes the first document that matches the condition and then skips over the second document. It then checks the third document and again skips over the fourth. Any idea what's going on?

**Comment by sivagollapalli** [comment]
```
def delete_if
    if block_given?
       target.each do |doc|
          delete(doc) if yield(doc)
           count += 1
      end
          self
      else
         super
      end
    end
```

When I check the method with the spec that has been specified above PR it gives `6` when you do `target.count` but loop iterates only 4 times. I didn't able to find out the reason. Could anyone help me so that I would try to fix this issue.

**Comment by knovoselic** [comment]
I think it's because you shouldn't modify array while you're iterating over it.

**Comment by sivagollapalli** [comment]
@arthurnn I have fixed the issue. May I know your comments on this pull?
