### ISSUE TITLE
getLastError does not report all inserts which have failed

### ISSUE THREAD

**Issue by harshitsk** [mongoid/mongoid#3976]
According to the latest release of mongoDB the getLastError command reports all inserts which have failed. As you can see from the below links.

https://jira.mongodb.org/browse/SERVER-9038

http://docs.mongodb.org/manual/release-notes/2.0/

The raw mongo-ruby-driver provides this feature. 

https://github.com/mongodb/mongo-ruby-driver/wiki/Bulk-Write-Operations

How can I get a report of all the failed inserts in Moped or Mongoid 4? or do I have to resort into the raw mongo ruby driver for this?

**Comment by harshitsk** [comment]
For now I am using Moped session command which returns an output object with writeErrors.

**Comment by estolfo** [comment]
Hi @harshitsk 

There is a new Ruby driver release candidate available from MongoDB as the gem mongo 2.0. It will be fully released this week.

Mongoid 5.0 will use this driver so you'll have the requested functionality in it. This will not be added to moped or Mongoid 4.

Feel free to try out the new ruby driver and keep your eye out for Mongoid 5, which will be released soon as well.

Emily
