### ISSUE TITLE
For GeoJSON point object, distance units is still treat as radians, not meters

### ISSUE THREAD

**Issue by veetase** [mongoid/mongoid#3978]
mongoid version: 4.0.1
The query is as followed:
```ruby
  spots = Spot.geo_near([params[:x].to_i, params[:y].to_i]).max_distance(params[:distance].to_i).spherical
```

**Comment by durran** [comment]
The max distance is in radians because this is querying on a legacy coordinate pair. If you want to query in meters you need to actually provide a GeoJSON object - what is shown here is not.
