### ISSUE TITLE
Delete field from Mongoid model at runtime.

### ISSUE THREAD

**Issue by mamantoha** [mongoid/mongoid#3981]
Hello everyone!
I have a question.

Does anybody else want to be able to delete the field from a model at runtime using standard Mongoid gem?

E.g:

```
Model.remove_field(:name)
```

Or possibly, a better idea would be to write the code for this feature as an additional plugin/extension?
Thanks.

**Comment by kuldeepaggarwal** [comment]
Why do you want to add/remove field dynamically?

**Comment by arthurnn** [comment]
I am not sure this is a valid use case TBH.
At the moment, you can define a Model with the fields, or use dynamic fields http://mongoid.org/en/mongoid/v3/documents.html#dynamic_fields

**Comment by mamantoha** [comment]
I need and all. But it was just a question. I understand. Ok :)
