### ISSUE TITLE
Support for Mongo v3.0.0 will bring new changes?

### ISSUE THREAD

**Issue by davidcunha** [mongoid/mongoid#3982]
Hi all,

Since there is a new major version out there, will it bring changes and a new version of mongoid?

Thanks

**Comment by estolfo** [comment]
Hi @davidcunha 

We have rewritten the MongoDB Ruby driver and it has been released as 2.0.0-beta. It supports MongoDB v3.0.0.
The next major version of Mongoid (5.0) will use this driver instead of Moped so it will support MongoDB v3.0.0.

**Comment by arthurnn** [comment]
thanks @estolfo
