### ISSUE TITLE
You can't add multiple embedded documents that are in embedded documents

### ISSUE THREAD

**Issue by jonhyman** [mongoid/mongoid#3991]
```ruby
class Test1
  include Mongoid::Document
  embeds_many :test2
end

class Test2
  include Mongoid::Document
  embedded_in :test1
  embeds_many :test3
end

class Test3
  include Mongoid::Document
  embedded_in :test2
end

# This all works fine
t = Test1.create
t.test2 << Test2.new
t.test2.first.test3.new
t.changed?
# => true
t.save

# This will now do nothing
t.test2.first.test3.new
t.changed?
# => false
t.test2.first.changed?
# => false
t.save
# returns true, yet it does nothing -- this is extremely dangerous/bad
t.test2.first.test3.last.persisted?
# => false
```

**Comment by muichkine** [comment]
@jonhyman that's a bug in mongodb: https://jira.mongodb.org/browse/SERVER-6864

**Comment by jonhyman** [comment]
No my pull fixes it. It's completely unrelated to that bug.

**Comment by jonhyman** [comment]
The issue here is mongoid doesn't even generate an update statement because it doesn't thing that the document has changed.

**Comment by jonhyman** [comment]
@durran can you add this to Mongoid 5? This bug is extremely bad for people who embed documents in embedded documents.

**Comment by durran** [comment]
@jonhyman Yeah I am working on this now - I have a solution that doesn't have to remove the memoization.

**Comment by jonhyman** [comment]
Thanks for doing that. We've been running a fork with my commit applied,
will be nice to get off that. ;)
