### ISSUE TITLE
ArgumentError: wrong number of arguments (2 for 1)  incrementable.rb:23:in `inc'

### ISSUE THREAD

**Issue by sselvamani22** [mongoid/mongoid#3999]
I am using mongoid (4.0.0)

I have a modal and here the code in my model
````
class Contact
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip
  include Mongoid::History::Trackable
  include ActiveSupport::Callbacks
  include ActiveModel::MassAssignmentSecurity

  field :first_name, type: String
  field :middle_name, type: String
  field :last_name, type: String
  field :picture_url, type: String

end
````

When I start console and run bellow code I receive an error as `ArgumentError: wrong number of arguments (2 for 1)` But save function works fine. It saved the data. But error throws. 
````
c = Contact.last
c.first_name = "Selva"
c.save

ArgumentError: wrong number of arguments (2 for 1)
from /home/loginadmin/.rvm/gems/ruby-2.2.0/gems/mongoid-4.0.0/lib/mongoid/persistable/incrementable.rb:23:in `inc'
````

**Comment by sselvamani22** [comment]
Fixed.

In my code I was using `self.inc(:range, 1)`. So now I changed to `self.inc(:range => 1)`. It seems they have changed format of the parameter.

**Comment by kuldeepaggarwal** [comment]
`Model#inc` accepts an `hash` as per the [documentation](http://mongoid.org/en/mongoid/docs/persistence.html#atomic). So, I think we can close this issue. wdyt?

**Comment by sselvamani22** [comment]
yeah.

**Comment by arthurnn** [comment]
thanks @kuldeepaggarwal
