### ISSUE TITLE
Incorrect behavior when chaining multiple `where` on the same field

### ISSUE THREAD

**Issue by calfzhou** [mongoid/mongoid#4002]
When chaining two `where` criteria on the same field, former ones will be ignored, which should be a bug.

For example, `User.where(role: 1).where(role: 2)` now generates `selector: {"role"=>2}`, but the expected result should be `selector: {"role"=>{"$in"=>[]}}`.

Other examples:

`User.where(role: 1).in(role: [2, 3])` generates `selector: {"role"=>{"$in"=>[]}}`, this is correct. But `User.in(role: [2, 3]).where(role: 1)` generates `selector: {"role"=>1}`, which should not be right.

`User.in(role: [1, 2]).in(role: [2, 3])` can correctly generate `selector: {"role"=>{"$in"=>[2]}}`, but `User.where(:role.in => [1, 2]).where(:role.in => [2, 3])` generates `selector: {"role"=>{"$in"=>[2, 3]}}`.

**Comment by kuldeepaggarwal** [comment]
@arthurnn I would like to work on this, but please give your views on this issue.

**Comment by gkuhn1** [comment]
i'm having this same issue.
Here, is a GIST to represent this issue:
https://gist.github.com/gkuhn1/ff03b92649628c5505fe

**Comment by durran** [comment]
Opened issue in origin for this:

https://github.com/mongoid/origin/issues/109
