### ISSUE TITLE
Insert very slow compared to mongo-ruby-driver

### ISSUE THREAD

**Issue by davidcunha** [mongoid/mongoid#4003]
Hi,

I'm working on an application that has a model called Ride with a :embeds_many relation with another model called Record. My app receives a big JSON coming from a parser and basically I would execute:

```ruby
Ride.create!(big_json_response)
```

Inside the JSON object there are some properties from the Ride and an array of Records (more than 10K in some cases). However I was experiencing a very slow insertion of a Ride (more than 16 seconds sometimes).
Since I removed MongoID and used directly the mongo-ruby-driver I saw a big decrease to 1, 2 seconds at max. Using a bulk insert of the Records would have helped?

Setup: MacBook Air, 1,3 GHz Intel Core i5, 4 GB 1600 MHz DDR3,
           MongoID 4.0.1, tried with Mongo 2.6 and Mongo 3.0 

Cheers

**Comment by kuldeepaggarwal** [comment]
Can you please create a sample application with some data and benchmarks to show the result, so that we can find the actual root cause.

**Comment by arthurnn** [comment]
@davidcunha : The idea is to move back to the main mongodb driver.. @durran is working on making Mongoid compatible again with the main driver, and we are going to drop support to moped driver!

**Comment by kuldeepaggarwal** [comment]
Great :+1:

**Comment by davidcunha** [comment]
Ok guys. Thanks!
