### ISSUE TITLE
actionview ~> 4.2 triggers false Rails detection in Sinatra app

### ISSUE THREAD

**Issue by PaulMakepeace** [mongoid/mongoid#4005]
I'm using actionview in a Sinatra app and noticed a regression during `Mongoid.load!` from actionview 4.1.6 to 4.2 which pulls in a couple of rails-* gems,

    actionview (4.2.1)
      activesupport (= 4.2.1)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.1)

They are listed as dependencies in actionview 4.1.6 but not loaded it seems.

    shared/bundle/ruby/2.0.0/gems/mongoid-4.0.2/lib/mongoid/config/environment.rb:22:in `env_name': undefined method `env' for Rails:Module (NoMethodError)
        from shared/bundle/ruby/2.0.0/gems/mongoid-4.0.2/lib/mongoid/config/environment.rb:39:in `load_yaml'

`Rails` gets defined by these rails-* gem confusing mongoid into thinking it's a rails app but `Rails.env` isn't defined. A `&& defined?(Rails.env)` would catch it.

Workaround is `gem 'actionview', '~> 4.1.0'` in Gemfile.

**Comment by PaulMakepeace** [comment]
Ah, actually actionview 4.1.x *doesn't* have these rails-* dependencies which makes more sense.

**Comment by arthurnn** [comment]
I am not sure if this is a bug still? is it?
Also, how can I simulate it?

**Comment by PaulMakepeace** [comment]
Yes, it's recent:

app.rb:

```
#!/usr/bin/env ruby

require 'mongoid'
require 'action_view'
include ActionView::Helpers
puts "Rails? #{defined? Rails}"
Mongoid.load! '/dev/null'
```

Gemfile:
```
source 'http://rubygems.org'

gem 'actionview'
gem 'mongoid'
```

Run with,

`bundle exec ./app.rb`

Fails here with,

```
/Users/makepeace/.rvm/gems/ruby-2.1.2/gems/mongoid-4.0.2/lib/mongoid/config/environment.rb:22:in `env_name': undefined method `env' for Rails:Module (NoMethodError)
	from /Users/makepeace/.rvm/gems/ruby-2.1.2/gems/mongoid-4.0.2/lib/mongoid/config/environment.rb:39:in `load_yaml'
	from /Users/makepeace/.rvm/gems/ruby-2.1.2/gems/mongoid-4.0.2/lib/mongoid/config.rb:83:in `load!'
	from /Users/makepeace/.rvm/gems/ruby-2.1.2/gems/mongoid-4.0.2/lib/mongoid.rb:99:in `load!'
	from ./app.rb:10:in `<main>'
```
