### ISSUE TITLE
Eager loading runs N queries when iterating 2+ times over the result set

### ISSUE THREAD

**Issue by p-run** [mongoid/mongoid#4006]
Consider this code:

<pre>
# _id is required in mongoid 4.0.2
models = Model.only(:name, :make, :_id).includes(:make)
# one query for all models, eager loading works
models.each do |model|
  puts model.make.name
end

# one query per model, eager loading does not work
models.each do |model|
  puts model.make.name
end
</pre>

I request that makes are loaded with models. In the first loop on models, there is one query for models and one query for makes for the entire loop. Then I run the loop again, and in the second loop I get one query per model to get the make.

Complete example + log can be seen here: https://gist.github.com/p-run/daafc2598867945cf642

**Comment by brauliomartinezlm** [comment]
I think this is the same issue as #3942.

**Comment by p-run** [comment]
@brauliomartinezlm this appears to be the case!
