### ISSUE TITLE
Floating point numbers pass validation in integer columns when they should not

### ISSUE THREAD

**Issue by p-run** [mongoid/mongoid#4008]
Consider the following code:

<pre>
require_relative '../../config/environment'

class Charge
  include Mongoid::Document
  
  field :amount, type: Integer
  
  validates :amount,
    :numericality => { :greater_than => 0, :less_than => 10 }
end

charge = Charge.new(amount: 0.5)
p charge
charge.save!
p charge.amount

charge = Charge.new(amount: 0)
p charge
charge.save!
</pre>

Actual result:

<pre>
% ruby script/dev/mongoid-validation-test.rb
#<Charge _id: 55106c8f6f79737fc9000000, amount: 0>
0
#<Charge _id: 55106c8f6f79737fc9010000, amount: 0>
/home/me/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/mongoid-4.0.2/lib/mongoid/persistable.rb:78:in `fail_due_to_validation!':  (Mongoid::Errors::Validations)
Problem:
  Validation of Charge failed.
Summary:
  The following errors were found: Amount must be greater than 0
Resolution:
  Try persisting the document with valid data or remove the validations.
	from /home/me/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/mongoid-4.0.2/lib/mongoid/persistable/savable.rb:45:in `save!'
	from script/dev/mongoid-validation-test.rb:19:in `<main>'
</pre>

I require amount to be numerical and greater than zero. Then I set amount to 0.5. This amount is persisted as 0, yet mongoid does not raise a validation error for this value. When I inspect the value on the model instance it is always 0 rather than 0.5, thus I am very confused how this value manages to pass validation.

**Comment by kuldeepaggarwal** [comment]
This [issue](https://github.com/rails/rails/issues/9957) is actually an activemodel issue and already in discussion.

**Comment by p-run** [comment]
In the above code I specify column type in the model, hence, mongoid knows it. No need to talk to the database.

Perhaps a different, mongoid-specific validator which takes into account the declared column type would be an acceptable solution.

**Comment by estolfo** [comment]
As per this issue, https://github.com/mongoid/mongoid/pull/2839, the type-casted attribute is used for validation. It's the same behavior issue in Active Record/Model (https://github.com/rails/rails/issues/9957) and Mongoid will remain consistent with it.
