### ISSUE TITLE
duplicate key error index

### ISSUE THREAD

**Issue by chukitow** [mongoid/mongoid#4010]
I have the following collections

```
class BaseModel
  include Mongoid::Document
  include Mongoid::Paranoia

  field   :name,            :type => String
  field   :description,     :type => String
end
```

```
class ModelA < BaseModel
  after_save :create_temporary_node

  def create_temporary_node
    self.attributes.delete(:id)
    model_b             = ModelB.find_or_initialize_by(id: id)
    model_b.id          = Moped::BSON::ObjectId(id)
    model_b.name        = self.name
    model_b.description = self.description
    model_b.save
  end
end
```

```
class ModelB
  include Mongoid::Document
  include Mongoid::Paranoia

  field   :name,            :type => String
  field   :description,     :type => String
end
```

When a row from ModelA is created automatically is created a row from ModelB; ModelB is used to restore and update information to ModelA

``` 
a = ModelA.create({name: 'lorem', description: 'ipsum'})
```

```
#<ModelA _id: 5512108d0310e97bab000001, deleted_at: nil, name: "lorem", description: "ipsum", _type: "ModelA">
```

```
b = ModelB.find('5512108d0310e97bab000001')
```

If I update attributes from ModelB

```
b.update_attributes(name: 'new name')
```

I'm able to update the attributes to ModelA with ModelB attributes

```
a.update_attributes(b.attributes)
=> true
```

But if ModelB is soft-deleted and I tried to to update ModelA attributes I receive this error

```
Moped::Errors::OperationFailure: The operation: 
#<Moped::Protocol::Command
 @length=82
@request_id=5
@response_to=0
@op_code=2004
@flags=[]
@full_collection_name="thrive_development.$cmd"
@skip=0
@limit=-1
@selector={:getlasterror=>1, :safe=>true}
@fields=nil>
failed with error 11000: "insertDocument :: caused by :: 11000 E11000 duplicate key error
index: thrive_development.model_bs.$_id_  dup key: { : ObjectId('5512108d0310e97bab000001'
) }"
```

**Comment by brauliomartinezlm** [comment]
I think the error is being correctly raised in this case.

If the instance of ModelB is soft-deleted, then when you try to save the corresponding instance of ModelA, the find_or_initialize_by won't find the soft-deleted instance of ModelB, and will try to create and save a new one with an id already used by the soft-deleted instance (which still exists in Mongo, hence the duplicated key).

Either you hard delete the instance of ModelB or unscope the find_or_initialize_by in which case the soft-deleted instance will be the one being saved in the after_save hook.

**Comment by estolfo** [comment]
From reading your description-- as @brauliomartinezlm said-- this error is expected.

Your method #create_temporary_node will do a search via find_or_initialize_by(id: id) for a ModelB with the same id as the ModelA. The 'soft-deleted' ModelB will not be returned, though it still exists in the collection.
When you try to reinsert the ModelB with the same id as ModelA (and thus the same id as the ModelB in the collection that hasn't *actually* been deleted), you'll get a duplicate key error.

I haven't been able to recreate the error so was wondering if you could send me the exact code you use to soft-delete ModelB and the exact line you use to update the attributes on ModelA?
