### ISSUE TITLE
Can't perform query with $maxTimeMS

### ISSUE THREAD

**Issue by chamnap** [mongoid/mongoid#4013]
I tried to call `#extras` with [$maxTimeMS](http://docs.mongodb.org/manual/reference/operator/meta/maxTimeMS/), but it doesn't perform the query with that extra mongodb operator.

```
[1] pry(main)> Yoolk::Mongo::Listing.where(name: "1").extras("$maxTimeMS" => 10000)
=> #<Mongoid::Criteria
  selector: {"name"=>"1"}
  options:  {"$maxTimeMS"=>10000}
  class:    Yoolk::Mongo::Listing
  embedded: false>
[2] pry(main)> Yoolk::Mongo::Listing.where(name: "1").extras("$maxTimeMS" => 10000).to_a
```

It takes ages to finish. What is the correct way to do?

**Comment by estolfo** [comment]
Hi @chamnap
You can't add arbitrary options via the #extras method on a Criteria. You are limited to :hint, :limit, :skip, :sort, :batch_size, :max_scan.

**Comment by chamnap** [comment]
@estolfo, do you accept the PR for this feature?

**Comment by estolfo** [comment]
Yes, but it also has to be an option in the underlying driver. We are going to add it to the new mongodb ruby driver https://github.com/mongodb/mongo-ruby-driver so you'll probably have to wait until it's available there first.

**Comment by estolfo** [comment]
Here is the jira ticket for the addition to the ruby driver, if you want to track when it's available.
https://jira.mongodb.org/browse/RUBY-888
