### ISSUE TITLE
accepts_nested_attributes_for not work for some operation

### ISSUE THREAD

**Issue by TangMonk** [mongoid/mongoid#4015]
# Embedded relation:

```ruby
class Abc
  include Mongoid::Document
  field :name
  embedded_in :user
end
```

```ruby
class User
  include Mongoid::Document
  embeds_many :abces, class_name: "Abc", cascade_callbacks: true
  accepts_nested_attributes_for :abces, :allow_destroy => true
```

rails console:

```ruby
     u = User.first
     u.abces_attributes=[{name: "123"}]
=> [{:name=>"123"}]

     u.abces
     [#<Abc _id: 55167a1e6c6f630fa1000000, name: "123">]

     u.abces_attributes=[{id: "55167a1e6c6f630fa1000000", _destroy: "1"}]
     # not deleted
     u.abces
=> [#<Abc _id: 55167a1e6c6f630fa1000000, name: "123">]
```

# Referenced relation

## has_many

1. first add works
2. but cannot update and add at next time
3. _destroy works

## has_one

1. add and destroy works, but cannot update for next time

rails 4.2 and mongoid 4.0

**Comment by estolfo** [comment]
Hi @TangMonk 

Can you see my comment here
https://github.com/mongoid/mongoid/issues/3920#issuecomment-87688097
and try changing the syntax you are using to update the attributes. As per the documentation here for embeds_many http://mongoid.org/en/mongoid/docs/nested_attributes.html

You should be using this format:

    u.abces_attributes = {
      "0" => { id: ..., _destroy: "1" },
    } 

Let me know if that works.

Emily
