### ISSUE TITLE
Some issues from a newer of mongoid

### ISSUE THREAD

**Issue by mingmingpao** [mongoid/mongoid#4017]
Hello, Everyone. 

I have researched mongoid for a few days, something is confusing me. 

Firstly, I havn't find any description of updated_at and created_at fields in ActiveRecord, doesn't mongoid support it, does it?

Secondly, can we change the primary key field _id to another name like id?

Thank you for your reply.

**Comment by brauliomartinezlm** [comment]
[Here](http://mongoid.org/en/mongoid/v3/extras.html#timestamps) you can find documentation about timestamps.

[Here](http://mongoid.org/en/mongoid/v3/documents.html#fields) you can read about using a custom id field at the "Create Custom Ids".

**Comment by mingmingpao** [comment]
Thank you for your reply. And the first solution is perfect for me, 
However, the second one is just changing the field type of _id but not 
changing the field name from _id to id.

I have attempted to use the Field Aliasing through the 'as' property, 
but leading to some strange phenomenons. Thus this is also not a good 
solution.

Thank you!

在 2015年03月30日 12:02, Braulio 写道:

**Comment by estolfo** [comment]
You can change the _id attribute to be a custom object instead of a BSON::ObjectId, but you can't change the name in the raw document saved to MongoDB. The _id field is required in each document and acts as a primary key.
You can read more about the _id field here
http://docs.mongodb.org/manual/core/document/#document-id-field

**Comment by mingmingpao** [comment]
Firstly, thank you for all your repies. 
I know that I cannot change the name '_id'. I hope mongoid framework can provide a mechanism to bind a alias to the default name '_id'. If so the database stores as _id while the ruby object stores id or some others. I expect such a capability.
