### ISSUE TITLE
recursively_embeds_many parent_* is always nil

### ISSUE THREAD

**Issue by artgo** [mongoid/mongoid#4018]
recursively_embeds_many does not embed parent into the document, more over, when you try to test parent_* == nil it always return true.
I need the parent more than children, so basically this is a blocker for me.

**Comment by estolfo** [comment]
Can you provide an example and your expectations for how this should work please? Thanks

**Comment by artgo** [comment]
Should it point to the parent on child records?

**Comment by durran** [comment]
Some sample code would be helpful in order to reproduce the problem. Your model definitions and the exact code to show that the parent is in fact nil would be a good start.

**Comment by durran** [comment]
Closing for no response, cannot replicate.
