### ISSUE TITLE
Multiple polymorphic relations of same type in one model

### ISSUE THREAD

**Issue by Jake0oo0** [mongoid/mongoid#4021]
I've been trying to solve this issue for the past few days, but I can't seem to find a way around it, and I don't know if there is a way. Any help is appreciated. 

I have my class Like:

```
class Like
  include Mongoid::Document
  belongs_to :likable, polymorphic: true
  belongs_to :user
end
```

```
class Submission
  include Mongoid::Document

  belongs_to :creator, class_name: 'User', inverse_of: :submissions
  has_many :likes, :as => :likable, :dependent => :destroy
end
```

Then the class that causes the problem:

```
class User
  include Mongoid::Document
  has_many :submissions, :dependent => :destroy

  has_many :liked_submissions, :as => :likable, :dependent => :destroy, class_name: 'Like'
  has_many :liked_comments, :as => :likable, :dependent => :destroy, class_name: 'Like'
end
```

Now, the problem is that I can't figure out how to properly have both 'liked_comments' and 'liked_comments' in the user class. When I have it as I do above I get the error: Ambiguous relations :liked_submissions, :liked_comments defined on User. when trying to create a like for a submission.

Is this possible, and if not, any suggestions to getting around it? I would like to use likes in a BlogPost model as well, but if this doesn't work, I'll have to find another way.

Thanks in advance.

**Comment by muichkine** [comment]
I'd say it is a design issue.

    The `like` of a submission or a comment is an attribute of the submission / comment. I don't know what your design is exactly but you could either:

    class LikableRelation
         belongs_to :user
         belongs_to :relation, :polymorphic => true
         field :liked, :type => :boolean
    end

and you use that as a has_many :through relation bridging users with comments / submissions. You could even leverage mongoid relation extensions to have :liked_submissions and liked_comments get you what you want easily.

**Comment by Jake0oo0** [comment]
@muichkine Does MongoID even support a ```:through``` relationship?

**Comment by comonitos** [comment]
Had tough times after discovering this issue but got cool solution that works 

**Add to your Gemfile**
> gem 'mongoid-multiple-polymorphic'


**And this works like a charm:**

      class Resource

      has_one :icon, as: :assetable, class_name: 'Asset', dependent: :destroy, autosave: true
      has_one :preview, as: :assetable, class_name: 'Asset', dependent: :destroy, autosave: true
      
      end
