### ISSUE TITLE
NoMethodError: undefined method `attr_protected' for User:Class

### ISSUE THREAD

**Issue by mingmingpao** [mongoid/mongoid#4027]
When I attempt to define User model like below 

    class User
        include Mongoid::Document
        field :first_name, type: String
        field :password, type: String
        attr_protected :password # focus this
    end

Then it throws the eroor NoMethodError of undefined method 'attr_protected'. Why?

Once I create new rails project through invoking command 'rails new blog_api --skip-active-record'

**Comment by larrylv** [comment]
I think you should not use `attr_protected` for mass assignment.

mongoid is using ActiveModel's `ForbiddenAttributesProtection` module for this now, I believe
https://github.com/mongoid/mongoid/blob/master/lib/mongoid/composable.rb#L33

**Comment by arthurnn** [comment]
@larrylv is right.
You should use mongoid 4 with strong parameters.

**Comment by mingmingpao** [comment]
But I do not know how to config it?

**Comment by larrylv** [comment]
@mingmingpao You don't need to configure it manually. Just use strong parameters.

**Comment by mingmingpao** [comment]
@larrylv Do you mean I need to controls these in my controllers? Yeah, I think it's a solution; however, I am afraid I have to write more codes.
