### ISSUE TITLE
MultiParameterAttributes not working.

### ISSUE THREAD

**Issue by AknEp** [mongoid/mongoid#4034]
In the document

```
If you want to use multi-paramater attributes with Rails, you will need to include an extra Mongoid module to support it.
...
include Mongoid::MultiParameterAttributes
```
http://mongoid.org/en/mongoid/docs/rails.html

but my very simple application (only including `Mongoid::MultiParameterAttributes`) occured `uninitialized constant Mongoid::MultiParameterAttributes`. What is my mistake?

**Comment by arthurnn** [comment]
MutiParameterAttributes was removed on Mongoid 4+ .
https://github.com/mongoid/mongoid/commit/5a72dd9f103ea25577389c9342d08181a96504a6

The docs are wrong, and we need to add a changelog entry for this.

**Comment by AknEp** [comment]
@arthurnn thanks.

then, how can I use `date_select` form helper with mongoid?
Why removed this feature?

**Comment by arthurnn** [comment]
@durran Do you have that answer?

**Comment by durran** [comment]
We're trying to decouple as much as possible dependencies in the persistence layer on view code. It's simply a bad pattern.

**Comment by simi** [comment]
I can try to gemify that.
Dne 14.4.2015 11:37 "AknEp" <notifications@github.com> napsal(a):
