### ISSUE TITLE
Embedded 1-1 relation doesn't work properly

### ISSUE THREAD

**Issue by EhsanYousefi** [mongoid/mongoid#4038]
I have 4 models(Job,Parcel,Action, Spec) with following relation
<pre><code>
class Job
  embeds_many :parcels
end
</code></pre>

<pre><code>
class Parcel
  embedded_in :job
end
</code></pre>

<pre><code>
class Action
  embed_one :spec
end
</code></pre>

<pre><code>
class Spec
  embedded_in :car
end
</pre></code>

When i create first record everything is ok, but after creating second record, spec returns nil.

In the end,  when i trying to save second record, mongoid updates first record spec instead of creating spec for new record.

**Comment by muichkine** [comment]
Your code is not sufficient to see any problem. Please add the use case.

**Comment by durran** [comment]
Closing - no response.
