### ISSUE TITLE
Strange Performance issues with where() vs find()

### ISSUE THREAD

**Issue by raphaelcm** [mongoid/mongoid#4044]
Mongoid 3.1.6
Rails 3.2.21
MongoDB 2.4.9

We're seeing strange performance issues with `find()` vs `where().first`:
```
$ rails c
2.1.5 :001 > Benchmark.ms { User.find('5091e4beccbce30200000006') }
 => 7.95 
2.1.5 :002 > Benchmark.ms { User.find('5091e4beccbce30200000006') }
 => 0.27599999999999997 
2.1.5 :003 > Benchmark.ms { User.find('5091e4beccbce30200000006') }
 => 0.215 
2.1.5 :004 > exit
```

```
$ rails c
2.1.5 :001 > Benchmark.ms { User.where(id: '5091e4beccbce30200000006').first }
 => 7.779999999999999 
2.1.5 :002 > Benchmark.ms { User.where(id: '5091e4beccbce30200000006').first }
 => 4.84 
2.1.5 :003 > Benchmark.ms { User.where(id: '5091e4beccbce30200000006').first }
 => 5.297 
2.1.5 :004 > exit
```

These both appear to be firing off the same queries. Can someone explain why we're seeing such a huge difference in performance?

Configuration:
```
production:
  sessions:
    default:
      uri: <%= REDACTED %>
      options:
        consistency: :strong
        safe: true
        max_retries: 1
        retry_interval: 0
  options:
    identity_map_enabled: true
```

Also asked this question on StackOverflow: http://stackoverflow.com/questions/29784093/strange-performance-issues-with-where-vs-find

**Comment by johnnyshields** [comment]
You need to look under the hood. Try using the .explain command and inspect the mongo logs to understand what queries are actually being generated.

**Comment by raphaelcm** [comment]
How exactly does one call `explain()` on `#find`? I've tried and can't figure it out.

AFAICT, `find` uses the identity map, while `where` does not, and that accounts for the difference. Is that wrong?

**Comment by johnnyshields** [comment]
Ah, yes, the identity would make sense here, since your first query with `find` takes 7 seconds and thereafter it's immediately returned.

**Comment by durran** [comment]
Mongoid's query cache in Mongoid 4 would have fixed this issue. Will not be backported into 3.
