### ISSUE TITLE
Exception will exit the Rails app, how to avoid it ?

### ISSUE THREAD

**Issue by poc7667** [mongoid/mongoid#4047]
I got ` **'Client Error: Remaining data too small for BSON object'**`
This is buggy code ` model.collection.insert(@data_in_chunk)`

So I tried to use **Begin Rescue** to ignore the exception, but it didn't work.
How could I ignore the error from **Mogoid**

# Error message

	Moped::Errors::OperationFailure: The operation: #<Moped::Protocol::Command
	  @length=97
	  @request_id=10246
	  @response_to=0
	  @op_code=2004
	  @flags=[]
	  @full_collection_name="tw_development.$cmd"
	  @skip=0
	  @limit=-1
	  @selector={:getlasterror=>1, :w=>1}
	  @fields=nil>
	failed with error 10304: "Client Error: Remaining data too small for BSON object"

# Exceptinal code

      def bulk_insert_to_collection(collection_name)
        model = collection_name.capitalize.constantize.new
        begin
          model.collection.insert(@data_in_chunk)
        rescue Exception => e
          @@mongo_logger.error("File #{@file_path}: line of #{i} #{Time.now}")
        end
        @data_in_chunk = []
      end
      
      
# collection status

	> db.cds.stats()
	{
	        "ns" : "tw__development.cds",
	        "count" : 45214787,
	        "size" : 91876447184,
	        "avgObjSize" : 2032,
	        "numExtents" : 64,
	        "storageSize" : 93016583552,
	        "lastExtentSize" : 2146426864,
	        "paddingFactor" : 1,
	        "paddingFactorNote" : "paddingFactor is unused and unmaintained in 3.0. It remains hard coded to 1.0 for compatibility only.",
	        "userFlags" : 1,
	        "capped" : false,
	        "nindexes" : 1,
	        "totalIndexSize" : 1946730128,
	        "indexSizes" : {
	                "_id_" : 1946730128
	        },
	        "ok" : 1
	}

**Comment by durran** [comment]
What is `@data_in_chunk`? What exactly are you trying to insert?

**Comment by durran** [comment]
Closed for no response.

**Comment by lucke84** [comment]
We happen to have the same situation while doing something similar. Here's a snippet:

```ruby
# ...

begin
  # MyModel.build returns a new instance of MyModel
  items_to_insert << MyModel.build(param1, param2).attributes
rescue
  Rails.logger.error 'Could not generate my_model'
end

if items_to_insert.size > 0  
  Rails.logger.info "Inserting #{items_to_insert.size} my_models"

  MyModel.collection.insert(items_to_insert) # fails here!
end

# ...
```

and we get the following exception:

```
Exception: The operation: #<Moped::Protocol::Command @length=75 @request_id=114 @response_to=0 @op_code=2004 @flags=[] @full_collection_name="my_db.$cmd" @skip=0 @limit=-1 @selector={:getlasterror=>1, :w=>1} @fields=nil> failed with error 10304: "Client Error: Remaining data too small for BSON object" See https://github.com/mongodb/mongo/blob/master/docs/errors.md for details about this error. 
The operation: #<Moped::Protocol::Command @length=75 @request_id=114 @response_to=0 @op_code=2004 @flags=[] @full_collection_name="my_db.$cmd" @skip=0 @limit=-1 @selector={:getlasterror=>1, :w=>1} @fields=nil> failed with error 10304: "Client Error: Remaining data too small for BSON object" See https://github.com/mongodb/mongo/blob/master/docs/errors.md for details about this error.
```

Is it possible that, if the array of objects (attributes) to contains only one -probably small- object, MongoDB refuses to let us use the bulk insert?
