### ISSUE TITLE
MongoID inheritance design issue, Rails

### ISSUE THREAD

**Issue by azsam** [mongoid/mongoid#4056]
Let's say I have a model Person and another model Student < Person

Is it possible to pass a json to Person with a property: _type: "Student" and to get a Student object? Can not get it working, is it a design issue or I don't get it?

Person.new {name: "John", _type: "Student"} returns a Person, not a Student...

**Comment by muichkine** [comment]
`Person.new`naturally returns a `Person` object.

You should be using Rails `constantize` or `safe_constantize` http://apidock.com/rails/String/constantize

so it goes

input = "Student"
input = input.safe_constantize
user = if input
             input.new :name => 'John'
           end

You can add some logic checking that `Student` is a child class of `Person` if you wish so.

Such a code can be put in `Person` class method to remain clean.

**Comment by azsam** [comment]
Hey,
thanks!
