### ISSUE TITLE
Where should I place my extend code of mongoid in my rails project?

### ISSUE THREAD

**Issue by mingmingpao** [mongoid/mongoid#4059]
I want to change the logic of mongoid's to_json by following code:

```ruby
module Mongoid
  module Document
    def as_json(options={})
      attrs = super(options)
      attrs["id"] = self.persisted? ? self._id : nil
      attrs
    end
  end
end
```

where should I place it? So far I place it in application.rb and it can be loaded when starting rails. However, I want to move it to other place, where should I move to?

**Comment by durran** [comment]
That's really up to you. In Rails projects a common place to put these is in `/lib`.
