### ISSUE TITLE
Weird issue with a fresh install

### ISSUE THREAD

**Issue by hartator** [mongoid/mongoid#4061]
I've just started a fresh Rails app (`4.2.1`) with fresh Mongoid (`4.0.2`) and a fresh install of MongoDB (`4.0.2`). (I've been using Mongoid for year now thanks for the excellent work! :) )

With this as Mongoid config: https://gist.github.com/hartator/f6384be95b67566c9e2e and this as simple test model: https://gist.github.com/hartator/63fc900086f6d2903b92

I keep getting:
`irb(main):001:0> Blur.create(name:'Sacha')
D, [2015-05-10T20:34:49.816124 #1124] DEBUG -- :   MOPED: 183.60.162.9:27017 COMMAND      database=admin command={:ismaster=>1} runtime: 10015.5830ms
Moped::Errors::ConnectionFailure: Could not connect to a primary node for replica set #<Moped::Cluster:70316227429040 @seeds=[<Moped::Node resolved_address="183.60.162.9:27017">]>`

The weird thing, `183.60.162.9` is not my ip (not local and not the ISP one). It's a weird chinese IP.

I don't get why it doesn't work and specialy why it's trying to connect this IP, any clues?

I've tried restarting several times, I don't think I have any viruses, digging into my local gems, looking for the IP in every files without any luck. :/

**Comment by durran** [comment]
Have you looked at your hosts file and perhaps localhost is resolving somewhere else?

**Comment by narutosanjiv** [comment]
@hartator  Can you access 183.60.162.9 port '27017'? Most of server do open all port for outside world.

**Comment by hartator** [comment]
Actually, my bad. My localhost does weirdly resolves to `183.60.162.9`. It's like a cellphone in China... (First time I am now running an antivirus on my mac...)

Anyway, it's not at all linked to Mongoid. Sorry about that. Closing the ticket. :/
