### ISSUE TITLE
Publish a 3.1.8 build to Rubygems

### ISSUE THREAD

**Issue by Benjamin-Dobell** [mongoid/mongoid#4062]
The "warnings" fixed in the commit:
https://github.com/mongoid/mongoid/commit/545713b0d663c8c6fcc32fa50fdf27ccc895b5db
aren't just warnings, they're errors.

In particular:
https://github.com/mongoid/mongoid/commit/545713b0d663c8c6fcc32fa50fdf27ccc895b5db#diff-2a1ba20c535d3b8eb4734a5544e21aa7L74
legitimately does not work with Ruby 2.2, field ends up nil - and breaks AddToSet operations (and probably a heap more).

Given Mongoid 3 does not work with Ruby 2.2 and above, could we please get a new 3.1.x version pushed out to Rubygems?

**Comment by arthurnn** [comment]
Do you mean 3.1.7?
This is the changeset https://github.com/mongoid/mongoid/compare/v3.1.6...3.1.0-stable 
seems safe to me.. I will release it today still.

**Comment by arthurnn** [comment]
3.1.7 released https://rubygems.org/gems/mongoid/versions/3.1.7
