### ISSUE TITLE
stroring an encrypted BSON::Binary

### ISSUE THREAD

**Issue by benams** [mongoid/mongoid#4064]
I started using mongodb in my application and I'm now looking for an easy way to encrypt some sensitive binary data and store it in the mongodb. When I do it for my MySql DB I use the attr_encrypted, but I guess that with mongoid, I'll need some other gem or method to do it, especially with a non-string field (BSON::Binary ).

Any suggestions?

**Comment by durran** [comment]
There's no way out fo the box to do encryption with Mongoid (we don't have an `attr_encrypted`), so I would recommend encrypting your value before setting it in a field as either a `BSON::Binary` or as a `String`.
