### ISSUE TITLE
authentication failed failed with error 13: "not authorized for insert on 

### ISSUE THREAD

**Issue by rajcybage** [mongoid/mongoid#4068]
After mongod.cnf auth=true  

I got

 ````
   Moped::Errors::OperationFailure: The operation: #<Moped::Protocol::Command
  @length=83
  @request_id=5
  @response_to=0
  @op_code=2004
  @flags=[]
  @full_collection_name="mongose_development.$cmd"
  @skip=0
  @limit=-1
  @selector={:getlasterror=>1, :w=>1}
  @fields=nil>
failed with error 13: "not authorized for insert on mongose_development.people"

See https://github.com/mongodb/mongo/blob/master/docs/errors.md
for details about this error.
	from /home/rajarshi/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/bundler/gems/moped-10abbf3eac37/lib/moped/operation/read.rb:50:in `block in execute'
	from /home/rajarshi/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/bundler/gems/moped-10abbf3eac37/lib/moped/node.rb:594:in `[]'
	from /home/rajarshi/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/bundler/gems/moped-10abbf3eac37/lib/moped/node.rb:594:in `block (2 levels) in flush'
	from /home/rajarshi/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/bundler/gems/moped-10abbf3eac37/lib/moped/node.rb:593:in `map'
	from /home/rajarshi/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/bundler/gems/moped-10abbf3eac37/lib/moped/node.rb:593:in `block in flush'
	from /home/rajarshi/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/bundler/gems/moped-10abbf3eac37/lib/moped/node.rb:617:in `block in logging'
	from /home/rajarshi/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `block in instrument'
	from /home/rajarshi/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrumen

`````

I have user with `dbowner` permission

and I am using the username and password.

It did not throw error in 

mono shell there it is working fine

**Comment by rajcybage** [comment]
the error had been fixed on 8a7719f but now it came back again

**Comment by rajcybage** [comment]
https://github.com/mongoid/moped/issues/375

**Comment by durran** [comment]
Closing as we have the Moped bug... Also will be fixed with Mongoid 5 (the next release) and the new driver.

**Comment by PushAppsService** [comment]
When is Mongoid 5 scheduled to be released?

**Comment by durran** [comment]
I'm estimating in a few weeks.

**Comment by PushAppsService** [comment]
Is this already supposed to be resolved in the mongo-ruby-driver-2 branch?
I can report that this issue still exists there.

I added to Gemfile: gem 'mongoid', github: "mongoid/mongoid", branch: "mongo-ruby-driver-2"
and removed any reference to the Moped gem

and still got the same exact error.

Thanks

**Comment by durran** [comment]
Have you set the appropriate `auth_source` for the user in the config? By default it's going to auth against the admin database but if the user is specific to a database you will have to provide `auth_source` with the database name.

**Comment by PushAppsService** [comment]
can you please point me to the documentation regarding auth_source ? Couldn't find it anywhere? Is it part of the new release? If so can you show an example of how to use it the mongoid.yml ?
Thanks

**Comment by durran** [comment]
It will be part of the new 5.0.0 release. There is no Mongoid documentation on it yet but the driver documentation on options is here: http://docs.mongodb.org/ecosystem/tutorial/ruby-driver-tutorial/#ruby-options

**Comment by o-r-r** [comment]
Hi @durran , this still happens with the mongo-ruby-driver-2 branch branch when the configuration in mongoid.yml looks like that:
```ruby
      username: valid_username
      password: valid_password
      auth_source: my_db_name
```

Should we open the issue in that branch?

**Comment by durran** [comment]
@o-r-r Try using `user` instead of `username`.

**Comment by smanvi** [comment]
So, I am new to mongo db on rails and Im getting the same error.

I have a user on admin db with role = 'root'

and in my mongoid.yml I am using ->

          username: <proper username>
          password: <proper password>
          auth_source: admin

I tried what @durran suggested, changing the "username" to "user" , but I still get the same error.

So do I need to wait for the Mongoid 5 release, or am I doing something wrong?

Any help would be appreciated.

**Comment by o-r-r** [comment]
I've changed to user, instead of username. Still receiving the same error:
**Mongo::Error::OperationFailure: not authorized on db-name to execute command {.........} (13)**
Isn't it a common case to work with authentication enabled in mongo? Do you have a test we can try running to see results in our environment? Thanks

**Comment by durran** [comment]
All the tests in the Mongoid test suite run with authentication on... You can see our users here:

https://github.com/mongoid/mongoid/blob/master/spec/support/authorization.rb

And our config for all specs:

https://github.com/mongoid/mongoid/blob/master/spec/config/mongoid.yml
