### ISSUE TITLE
Throw error in Aggregate

### ISSUE THREAD

**Issue by emmanuelmillionaer** [mongoid/mongoid#4074]
Lets say i have this code:

```ruby
map = %Q{
  function() {
    emit(this.name, { likes: this.likes });
  }
}

reduce = %Q{
  function(key, values) {
    var result = { likes: 0 };
    values.forEach(function(value) {
      if(value.likes < 0){
          #{Rails.logger.error "likes are negativ" }
      }
      result.likes += value.likes;
    });
    return result;
  }
}

Band.where(:likes.gt => 100).map_reduce(map, reduce).out(inline: true)
```

As you can see I want to record an error if the `value.likes` are negativ:

    #{Rails.logger.error "likes are negativ" }

But this Code is executed each time I run the aggregate and not when the `likes` are negativ.

### What can I do to throw an error in the aggregate statement? 

Thanks

Stackoverflow: http://stackoverflow.com/questions/30376363/throw-error-in-mongoid

**Comment by durran** [comment]
You cannot do that. The javascript is executed on the server side and has no correlation with the client.

**Comment by narutosanjiv** [comment]
@durran What if we use popen3 to execute this?

**Comment by durran** [comment]
That still doesn't change the fact that the Javascript is executed on the server - it knows nothing about the calling process. The only way to get any sort of logging would be to use `print` in the reduce function, which would write to the server log, but there's no way to get anything in the Rails/application log.
