### ISSUE TITLE
Mongoid.purge! doesn't work with WiredTiger

### ISSUE THREAD

**Issue by nofxx** [mongoid/mongoid#4080]
Working fine with MMAP:

    Mongoid.purge!

But nothing gets deleted when using wiredtiger,  also:

    Mongoid.default_session.collections # => []

This works:

    Mongoid.default_session.drop

**Comment by durran** [comment]
Can you confirm this is not an issue on master? Mongoid won't support WiredTiger until we release 5.0.0 since Moped doesn't support MongoDB higher than 2.6.

**Comment by nofxx** [comment]
Working fine on master. Sorry bother.
