### ISSUE TITLE
Mongoid.purge in Rspec drop all database (test, development)

### ISSUE THREAD

**Issue by lovedota** [mongoid/mongoid#4085]
Hi guys
I recently upgraded from Rails 3.2 to 4.2.1. My **spec_helper,rb**
```
  config.after(:each) do
    Mongoid.purge!
  end
```
After run **rspec** the database development is dropped too. Is there anyway to run **Mongoid.purge!** in specific database like **Mongoid.purge!test**
Here is my **rspec**
```
group :test, :development do
  gem "rspec-core", '~> 2.14.0'
  gem "rspec-rails", '~> 2.14.0'
  gem 'factory_girl_rails', require: false
  gem 'pry-byebug'
  gem 'pry-stack_explorer'
  gem 'spring'
  gem "spring-commands-rspec"
  gem 'quiet_assets'
  gem 'awesome_print'
end
```
Thanks !
```

**Comment by durran** [comment]
Can you show how this is happening? `purge!` only drops each collection in the default session - if you're in the test env that would be the only one dropped. I cannot replicate this myself.

**Comment by lovedota** [comment]
@durran 
I resolved it. I don't know why this happen.
In Rails 3, in spec_helper, I put the **ENV["RAILS_ENV"] ||= 'test'** after all the **require** it worked well, and when upgrade to Rails 4, it drops all database.
```
require File.expand_path("../../config/environment", __FILE__)
require 'best_in_place'
require 'best_in_place/test_helpers'
require 'rspec/mocks/standalone'
require 'suvt/suvt_constant'
require 'suvt/suvt_request_error'

ENV["RAILS_ENV"] ||= 'test'
```

- I put it in the top of the file, and it works well. 
Do we need to update document for it ? Thanks !

**Comment by durran** [comment]
I'll make sure the documentation is clear. Thanks.
