### ISSUE TITLE
Mongoid::Criteria does not return the associations of the collection

### ISSUE THREAD

**Issue by TheRealGuardDogGPS** [mongoid/mongoid#4087]
I use a few where condition to return a Mongoid::Criteria. The returned collection consists of Lead documents from my mongodb database. I only have one lead document in my collection. It has an associated contact (it belongs_to a contact). When I try to retrieve the contact, it gives me nil. This is what the Mongoid::Criteria looks like:

![mongoid_criteria](https://cloud.githubusercontent.com/assets/5922053/7951390/cfcbc184-0974-11e5-8325-5593fbd92c9e.png)

What is bizarre is that in the same request, I run Lead.first.contact and it correctly returns the contact. So I know that the contact association is there.

Why when I retrieve the Lead from Mongoid::Criteria, it is not finding the association?

**Comment by TheRealGuardDogGPS** [comment]
I discovered the problem here. When you use only to select only certain fields, if one of the fields left out is the association id e.g. contact_id, then that association will be left out of relationship. To me, this seems like a bug.

**Comment by durran** [comment]
That is by design - the value simply needs to be there in order to retrieve it. We cannot make assumptions to ensure all relation ids are there as that would not allow people to optimize when they do not want them.
