### ISSUE TITLE
A security issue

### ISSUE THREAD

**Issue by mkaschenko** [mongoid/mongoid#4092]
@durran 
There is the [article](http://sakurity.com/blog/2015/06/04/mongo_ruby_regexp.html) has been published a few days ago on the internet. 
Did you see it?

**Comment by durran** [comment]
Yes, and `bson` 3.0.4 was released with a patch for it. If you're on Mongoid 4, then bundle update to get the latest BSON gem. If you're on Mongoid 3, Moped 1.5.3 was patched with a fix and bundle update to get the latest moped.
