### ISSUE TITLE
Mongoid 5 #with changes bleeding across queries (and slave_ok all the time?)

### ISSUE THREAD

**Issue by jonhyman** [mongoid/mongoid#4097]
Hey @durran, I'm testing out Mongoid 5. I'm seeing that `Model.with` is changing the underlying session/client.

Here's a spec in Mongoid 4:

```ruby
it "doesn't change options" do
  Moped.logger = Logger.new(STDOUT)
  puts(Band.collection.database.session.options.inspect)
  Band.with(:read => :secondary_preferred).first
  puts(Band.collection.database.session.options.inspect)
  Band.first
  Band.with(:read => :primary).first
  puts(Band.collection.database.session.options.inspect)
  Band.first
end
```

and its output:

```
{:instrumenter=>ActiveSupport::Notifications, :database=>:mongoid_test}
D, [2015-06-18T18:53:12.978035 #26554] DEBUG -- :   MOPED: 127.0.0.1:27017 QUERY        database=mongoid_test collection=bands selector={"$query"=>{}, "$orderby"=>{:_id=>1}} flags=[:slave_ok] limit=-1 skip=0 batch_size=nil fields=nil runtime: 0.4600ms
{:instrumenter=>ActiveSupport::Notifications, :database=>:mongoid_test}
D, [2015-06-18T18:53:12.978597 #26554] DEBUG -- :   MOPED: 127.0.0.1:27017 QUERY        database=mongoid_test collection=bands selector={"$query"=>{}, "$orderby"=>{:_id=>1}} flags=[] limit=-1 skip=0 batch_size=nil fields=nil runtime: 0.3010ms
D, [2015-06-18T18:53:12.979045 #26554] DEBUG -- :   MOPED: 127.0.0.1:27017 QUERY        database=mongoid_test collection=bands selector={"$query"=>{}, "$orderby"=>{:_id=>1}} flags=[] limit=-1 skip=0 batch_size=nil fields=nil runtime: 0.2610ms
{:instrumenter=>ActiveSupport::Notifications, :database=>:mongoid_test}
D, [2015-06-18T18:53:12.979490 #26554] DEBUG -- :   MOPED: 127.0.0.1:27017 QUERY        database=mongoid_test collection=bands selector={"$query"=>{}, "$orderby"=>{:_id=>1}} flags=[] limit=-1 skip=0 batch_size=nil fields=nil runtime: 0.2260ms
```

This looks right. The first `Band.first` query has a `slave_ok`, then the remaining 3 do not have `slave_ok`. Inspecting `Band.collection.database.session.options` does not change across updates.

Here it is in Mongoid 5:

```ruby
it "doesn't change options" do
  Mongo::Logger.logger = Logger.new(STDOUT)
  puts(Band.collection.database.client.options.inspect)
  Band.with(:read => {:mode => :secondary_preferred}).first
  puts(Band.collection.database.client.options.inspect)
  Band.first
  Band.with(:read => {:mode => :primary}).first
  puts(Band.collection.database.client.options.inspect)
  Band.first
end
```

and its output:

```
{:database=>:mongoid_test, :server_selection_timeout=>0.5, :max_pool_size=>1, :heartbeat_frequency=>180, :user=>"mongoid-user", :password=>"password", :auth_source=>"admin", :hosts=>["127.0.0.1:27017"], :options=>{"server_selection_timeout"=>0.5, "max_pool_size"=>1, "heartbeat_frequency"=>180, "user"=>"mongoid-user", "password"=>"password", "auth_source"=>"admin"}}
D, [2015-06-18T18:51:13.296944 #26432] DEBUG -- : MONGODB | QUERY | namespace=mongoid_test.bands selector={} flags=[:slave_ok, :slave_ok] limit=0 skip=0 project=nil | runtime: 0.3798ms
{:database=>:mongoid_test, :server_selection_timeout=>0.5, :max_pool_size=>1, :heartbeat_frequency=>180, :user=>"mongoid-user", :password=>"password", :auth_source=>"admin", :hosts=>["127.0.0.1:27017"], :options=>{"server_selection_timeout"=>0.5, "max_pool_size"=>1, "heartbeat_frequency"=>180, "user"=>"mongoid-user", "password"=>"password", "auth_source"=>"admin"}, :read=>{:mode=>:secondary_preferred}}
D, [2015-06-18T18:51:13.297522 #26432] DEBUG -- : MONGODB | QUERY | namespace=mongoid_test.bands selector={} flags=[:slave_ok, :slave_ok] limit=0 skip=0 project=nil | runtime: 0.2320ms
D, [2015-06-18T18:51:13.297978 #26432] DEBUG -- : MONGODB | QUERY | namespace=mongoid_test.bands selector={} flags=[:slave_ok] limit=0 skip=0 project=nil | runtime: 0.2561ms
{:database=>:mongoid_test, :server_selection_timeout=>0.5, :max_pool_size=>1, :heartbeat_frequency=>180, :user=>"mongoid-user", :password=>"password", :auth_source=>"admin", :hosts=>["127.0.0.1:27017"], :options=>{"server_selection_timeout"=>0.5, "max_pool_size"=>1, "heartbeat_frequency"=>180, "user"=>"mongoid-user", "password"=>"password", "auth_source"=>"admin"}, :read=>{:mode=>:primary}}
D, [2015-06-18T18:51:13.298526 #26432] DEBUG -- : MONGODB | QUERY | namespace=mongoid_test.bands selector={} flags=[:slave_ok] limit=0 skip=0 project=nil | runtime: 0.2551ms
```

In this case, we see `slave_ok` in each query (in fact, we see it twice when it should be there just once). But if you look at `Band.collection.database.client.options`, the options do change after a `Band.with`. This is why the 2nd `Band.first` still has two `slave_ok`s! This seems really bad, as the secondary read is persisting across multiple queries.

Seems like there is 1, maybe 2 bugs here.

**Comment by durran** [comment]
That's interesting... I see the slave_ok flag but looking at the actual options the read mode is primary... Also the duplicate slave_ok flags is odd as well. I'm having a look.

**Comment by durran** [comment]
Okay first... With a cluster topology type of single, which in your case is true since there is only 1 server, the slave_ok flag will always be set no matter what your read preference is... The specification is here:

https://github.com/mongodb/specifications/blob/master/source/server-selection/server-selection.rst#topology-type-single

That's just for clarification... There's still the issue with the double flags, and this is still an issue if you were using a replica set... Also note this is not a bug in Mongoid but with the core driver itself - I'm working now on a fix.

**Comment by jonhyman** [comment]
Thanks for the note. I'm going to do some testing later today, as we host with ObjectRocket and they use load balancers in front of their mongos (which is acceptable per the [documentation](http://docs.mongodb.org/manual/core/sharded-cluster-architectures-production/)). As such, we only use a single connection string per cluster to the load balancer, which then internally routes to multiple mongoS's; based on a quick glance reading that, I'm worried that such architecture setups will cause a `slave_ok` to always be set, which would be extremely bad for us. But I'll take a look and update this ticket.

The `with` causes other options to bleed over as well. If you do

```ruby
Band.with(:write => {:w => 0}).collection.find({}).update_one(:$set => {:foo => 'bar'})
Band.collection.find({}).update_one(:$set => {:foo => 'baz'})
```

then I believe both with go with a write-concern of 0. At least, so far in my specs for something we do, that is true based on the fact that the client's `options` do not revert back after the single query like they do in Mongoid 4. I'll also do more testing here and update the ticket.

**Comment by durran** [comment]
That won't be the case if the topology is mongos - we won't be sending the `slave_ok` in that case, even if it's just one load balancer in front of multiple mongos.

And you are correct, all options are not getting reset back - it wasn't just the read preference. The only options changes that were forcing the reset were `user` and `password`.

**Comment by durran** [comment]
Fix is here: https://github.com/mongodb/mongo-ruby-driver/commit/90525b13c65d512ea9528509243116c4dde78e1e

**Comment by jonhyman** [comment]
Thanks. I tried connecting to multiple ObjectRocket clusters yet it always sent `slave_ok`, I guess because it doesn't realize it's talking to a load balancer and a mongoS?

I filed the issue at https://jira.mongodb.org/browse/RUBY-949.

**Comment by jonhyman** [comment]
I don't think this issue is fixed, see https://jira.mongodb.org/browse/RUBY-967.
