### ISSUE TITLE
Error message translation with i18n

### ISSUE THREAD

**Issue by vonTronje** [mongoid/mongoid#4107]
When trying to translate validation error messages with i18n I was unable to change the titles for the 'problem', 'summary' and 'resolution' parts. The content can be easily changed, the titles however are hardcoded in [mongoid_error.rb] (https://github.com/mongoid/mongoid/blob/master/lib/mongoid/errors/mongoid_error.rb#L25-L27).
Sadly this makes translations into other languages weird.

I think it would be useful to allow setting these values via i18n locales as well. If you agree I'd be happy to supply a pull request.

Cheers
Hagen

**Comment by durran** [comment]
If you can do a pull request that would be great!

**Comment by vonTronje** [comment]
Sure. I will probably not get around to it before Sunday though.
