### ISSUE TITLE
rake db:mongoid:create_indexes does not create indexes in models defined in gems (Rails plugins)

### ISSUE THREAD

**Issue by TheR2** [mongoid/mongoid#4108]
I have observed this behaviour in version 4.0.2. It might have been also present in whole 4.0 version.

Only indexes defined in current application are checked and created.

by
TheR

**Comment by durran** [comment]
Mongoid by design only creates the indexes for anything that is under `app/models`. If you want to create indexes from an external source you will need to do this by hand or create your own rake task to do so.

**Comment by TheR2** [comment]
This is awkward. I have lots of indexes created in development and test which must have been created automatically by db:mongoid:create_indexes since I didn't created them manually. 
I have just recently discovered that indexes are not created in development and now also in production.
I will create a rake task to recreate indexes automatically.
byTheR
  


     On Friday, June 26, 2015 4:47 PM, Durran Jordan <notifications@github.com> wrote:
   

 Mongoid by design only creates the indexes for anything that is under app/models. If you want to create indexes from an external source you will need to do this by hand or create your own rake task to do so.—
