### ISSUE TITLE
Mongoid 5 & Sidekiq => many open connections

### ISSUE THREAD

**Issue by 256dpi** [mongoid/mongoid#4109]
I gave mongoid 5 a try in my app.

The rails side is working without problems, but the sidekiq process is constantly opening connections.
Only if I restart the process, the connections get closed.

I get the value from mongodb `serverStatus.connections.current` metric.

I use the following client settings in `mongoid.yml`:

```yaml
max_pool_size: 100
min_pool_size: 30
```

As I only upgraded the mongoid gem, I assume the problem is not depending on sidekiq.

**Comment by durran** [comment]
What is the number of connections that you are seeing and what is the expectation? Is this a single node or a replica set? Can I see sample code?

Also note that per server there will be 2 connections - 1 for operations and 1 for the server monitor which periodically updates the server's status. So in a single server setup, you will have at least double the number connections if the pool size is 1. `total connections = (current pool size + 1) * number of servers`

**Comment by 256dpi** [comment]
After 24 hours I had 11'000 open connections. Since then i'm restarting the worker process frequently. It's a single node installation with the latests MongoDB version. Sorry, code is private, but it's standard rails code with no special things.

One thing though: I launch jobs das frequently remove many records from collections, in that sense the operations sometimes take over 100ms, maybe there is a timeout triggering somewhere.

Can I provide more information? I will roll-back soon.

**Comment by durran** [comment]
Do you have a single worker? Multiple workers? How are they called? Are you instantiating a new client each time the worker executes or interacting with the database via the models directly? Have you tried calling `Mongoid.disconnect_clients` when the worker finishes executing?

I'll do some testing with a basic rails app and a sidekiq worker but I cannot guarantee I can find anything without example code... It doesn't have to be your exact code, just something similar to go on.

**Comment by 256dpi** [comment]
I have a main worker that gets scheduled by a clockwork process every 30 minutes:

```ruby
class RetentionLimiterScheduler
  include Sidekiq::Worker

  sidekiq_options retry: false

  def perform
    Namespace.all.each_with_index do |namespace, i|
      RetentionLimiter.perform_in((i * 10).seconds, namespace.id.to_s)
    end
  end
end
```

The other worker does the actual job:

```ruby
class RetentionLimiter
  include Sidekiq::Worker

  def perform(namespace_id)
    RetentionLimitation.new(Namespace.find(namespace_id)).limit!
  end
end
```

The service class 'RetentionLimitation' does just some things like:

```ruby
@namespace.messages.where(some_filters).delete_all
```

I haven't tried `Mongoid.disconnect_client`, is it threadsafe?

**Comment by rkyrychuk** [comment]
Have same problem with puma in threaded mode under load, connection are not reused and created only.

**Comment by 256dpi** [comment]
I can confirm @rkyrychuk, just tested with `siege` and saw the connection count rising.

**Comment by durran** [comment]
@256dpi @rkyrychuk Can you both retest against latest master. I removed the thread-local client storage in this commit: https://github.com/mongoid/mongoid/commit/5ff1bb816fe98ac198c548e2760cf785d58a8778

**Comment by 256dpi** [comment]
@durran The update solved the problem for me. Thanks!

**Comment by rkyrychuk** [comment]
@durran From the first glance everything is working as expected. Thanks.
