### ISSUE TITLE
Mongo ~> 2.1 versions does not exist

### ISSUE THREAD

**Issue by lndl** [mongoid/mongoid#4113]
Hi!

I've tried to update the mongoid repository to the latest commit in master branch with Bundler and it throws up the following dependency error:

```
Resolving dependencies...
Bundler could not find compatible versions for gem "mongo":
  In Gemfile:
    mongoid (>= 0) ruby depends on
      mongo (~> 2.1) ruby
Could not find gem 'mongo (~> 2.1) ruby', which is required by gem 'mongoid (>= 0) ruby', in any of the sources.
```

Mongoid gemspec specifies this dependency:

``` ruby
 s.add_dependency("mongo", ["~> 2.1"])
```

But the current version of mongo driver is 2.0.6
Thanks!

**Comment by durran** [comment]
You need to point at master of mongodb/mongo-ruby-driver until we release officially.
