### ISSUE TITLE
Default value on attributes makes the attribute dirty

### ISSUE THREAD

**Issue by darthdeus** [mongoid/mongoid#4115]
In mongoid 4.0.2

```ruby
class Foo
  include Mongoid::Document
  field :bar, default: 1
end
```

and then simply run

```ruby
> Foo.new.changed?
=> true
```

This seems like an obvious bug, just because it applies to `Foo.new`.

**Comment by durran** [comment]
A new document is *always* changed if any attributes exist, because it is not saved yet in the database and it's state is different from what the implied record in the database is.

**Comment by darthdeus** [comment]
@durran But this makes completely no sense. It defeats the purpose of having a `changed` property if it can't be used with mongoid's default values.

Especially having `Foo.new.changed?` be `true` ... shouldn't that by design be always `false`?
